  CREATE INDEX entr_seq ON entr(seq);
  CREATE INDEX entr_stat ON entr(stat) WHERE stat!=2;
  CREATE INDEX rdng_entr ON rdng(entr);
  CREATE INDEX rdng_txt ON rdng(txt);
  -- CREATE UNIQUE INDEX rdng_txt1 ON rdng(entr,txt);
  CREATE UNIQUE INDEX rdng_ord ON rdng(entr,ord);
  CREATE INDEX kanj_entr ON kanj(entr);
  CREATE INDEX kanj_txt ON kanj(txt);
  -- CREATE UNIQUE INDEX kanj_txt1 ON kanj(entr,txt);
  CREATE UNIQUE INDEX kanj_ord ON kanj(entr,ord);
  CREATE INDEX sens_entr ON sens(entr);
  CREATE UNIQUE INDEX sens_ord ON sens(entr,ord);
  CREATE INDEX gloss_sens ON gloss(sens);
  CREATE INDEX gloss_txt ON gloss(txt);
  -- CREATE UNIQUE INDEX gloss_txt1 ON gloss(sens,txt);
  CREATE UNIQUE INDEX gloss_ord ON gloss(sens,ord);
  CREATE INDEX xref_sens ON xref(sens);
  CREATE INDEX xref_xref ON xref(xref);
  CREATE INDEX hist_dt ON hist(dt);
  CREATE INDEX hist_who ON hist(who);
  CREATE INDEX audio_fname ON audio(fname);
  CREATE INDEX restr_rdng ON restr(rdng);
  CREATE INDEX restr_kanj ON restr(kanj);
  CREATE INDEX stagr_sens ON stagr(sens);
  CREATE INDEX stagr_rdng ON stagr(rdng);
  CREATE INDEX stagk_sens ON stagk(sens);
  CREATE INDEX stagk_kanj ON stagk(kanj);
  CREATE INDEX xresolv_sens ON xresolv(sens);
  CREATE INDEX xresolv_txt ON xresolv(txt);
  CREATE INDEX editor_email ON editor(email);
  CREATE UNIQUE INDEX editor_name ON editor(name);

