
# jelparse_tab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x95g\xa2q)4\x92\x1e\x87\xf7C\x87\x08\xa5\xc7z'
    
_lr_action_items = {'SEMI':([2,3,4,5,8,9,10,11,14,15,19,20,22,23,33,36,41,42,43,46,47,48,49,50,52,53,54,55,56,57,58,61,63,68,69,70,71,72,75,76,81,],[-13,-14,-5,13,-7,18,-9,-11,-8,-24,-12,18,-6,-25,-10,-26,-20,-18,59,-51,-47,-43,-49,65,-41,-53,-54,-46,-52,-22,-21,-48,-44,-55,-56,-23,-19,-50,-45,-42,-57,]),'NL':([0,2,3,4,5,8,9,10,11,12,14,15,19,20,22,23,33,36,],[1,-13,-14,-5,12,-7,17,-9,-11,21,-8,-24,-12,34,-6,-25,-10,-26,]),'KTEXT':([0,1,12,13,16,18,37,38,60,64,65,],[2,2,2,2,25,2,25,46,46,46,46,]),'RTEXT':([0,1,12,13,16,18,37,38,60,64,65,],[3,3,3,3,26,3,26,56,56,56,56,]),'SLASH':([51,],[66,]),'DOT':([46,47,48,49,53,54,56,68,69,72,],[-51,60,64,-49,-53,-54,-52,-55,-56,-50,]),'COMMA':([24,25,26,27,28,29,45,46,47,48,49,50,51,52,53,54,55,56,61,63,67,68,69,72,73,74,75,76,78,79,80,81,83,84,85,],[37,-29,-30,-31,-27,-32,-28,-51,-47,-43,-49,-38,-33,-41,-53,-54,-46,-52,-48,-44,-34,-55,-56,-50,-58,82,-45,-42,-35,-39,-40,-57,-36,-59,-37,]),'TEXT':([16,37,38,54,66,67,83,],[27,27,51,69,77,79,79,]),'GTEXT':([15,23,32,36,40,59,],[-24,-25,41,-26,57,41,]),'EQL':([27,],[38,]),'BRKTR':([24,25,26,27,28,29,45,46,47,48,49,50,51,52,53,54,55,56,61,63,67,68,69,72,73,74,75,76,78,79,80,81,83,84,85,],[36,-29,-30,-31,-27,-32,-28,-51,-47,-43,-49,-38,-33,-41,-53,-54,-46,-52,-48,-44,-34,-55,-56,-50,-58,81,-45,-42,-35,-39,-40,-57,-36,-59,-37,]),'SNUM':([15,17,21,23,30,31,34,35,36,39,41,42,43,44,57,58,70,71,],[-24,32,32,-25,-15,32,32,32,-26,-16,-20,-18,-17,32,-22,-21,-23,-19,]),'$end':([6,7,15,23,30,31,35,36,39,41,42,43,44,57,58,70,71,],[0,-1,-24,-25,-15,-3,-4,-26,-16,-20,-18,-17,-2,-22,-21,-23,-19,]),'NUMBER':([38,62,65,82,],[54,73,54,84,]),'HASH':([54,],[68,]),'COLON':([51,77,],[67,83,]),'BRKTL':([2,3,8,11,14,15,19,23,32,36,40,41,46,47,48,49,53,54,56,57,58,59,68,69,70,72,],[-13,-14,16,16,16,-24,16,-25,16,-26,16,16,-51,62,62,-49,-53,-54,-52,16,16,16,-55,-56,16,-50,]),'QTEXT':([16,37,38,60,64,65,67,83,],[29,29,53,53,53,53,80,80,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'entr':([0,],[6,]),'rdngitem':([1,12,18,],[10,10,33,]),'xrefnum':([38,65,],[48,48,]),'kanjitem':([0,13,],[4,22,]),'kanjsect':([0,],[5,]),'senses':([17,21,34,],[31,35,44,]),'tagitem':([16,37,],[28,45,]),'snums':([62,],[74,]),'taglist':([8,11,14,19,32,40,41,57,58,59,70,],[15,15,23,23,15,23,15,15,23,15,23,]),'dotlist':([38,64,65,],[47,47,47,]),'tags':([16,],[24,]),'rdngsect':([1,12,],[9,20,]),'taglists':([8,11,32,41,57,59,],[14,19,40,58,70,40,]),'atext':([67,83,],[78,85,]),'gloss':([32,59,],[42,71,]),'jtext':([38,60,64,65,],[49,72,49,49,]),'jrefs':([38,],[50,]),'sense':([17,21,31,34,35,44,],[30,30,39,30,39,39,]),'slist':([47,48,],[61,63,]),'jref':([38,65,],[52,76,]),'krtext':([0,1,12,13,18,],[8,11,11,8,11,]),'preentr':([0,],[7,]),'jitem':([38,64,65,],[55,75,55,]),'glosses':([32,],[43,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> entr","S'",1,None,None,None),
  ('entr -> preentr','entr',1,'p_entr_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',40),
  ('preentr -> kanjsect NL rdngsect NL senses','preentr',5,'p_preentr_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',76),
  ('preentr -> NL rdngsect NL senses','preentr',4,'p_preentr_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',80),
  ('preentr -> kanjsect NL NL senses','preentr',4,'p_preentr_3','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',84),
  ('kanjsect -> kanjitem','kanjsect',1,'p_kanjsect_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',88),
  ('kanjsect -> kanjsect SEMI kanjitem','kanjsect',3,'p_kanjsect_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',92),
  ('kanjitem -> krtext','kanjitem',1,'p_kanjitem_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',96),
  ('kanjitem -> krtext taglists','kanjitem',2,'p_kanjitem_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',100),
  ('rdngsect -> rdngitem','rdngsect',1,'p_rdngsect_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',107),
  ('rdngsect -> rdngsect SEMI rdngitem','rdngsect',3,'p_rdngsect_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',111),
  ('rdngitem -> krtext','rdngitem',1,'p_rdngitem_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',115),
  ('rdngitem -> krtext taglists','rdngitem',2,'p_rdngitem_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',119),
  ('krtext -> KTEXT','krtext',1,'p_krtext_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',126),
  ('krtext -> RTEXT','krtext',1,'p_krtext_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',130),
  ('senses -> sense','senses',1,'p_senses_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',134),
  ('senses -> senses sense','senses',2,'p_senses_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',138),
  ('sense -> SNUM glosses','sense',2,'p_sense_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',142),
  ('glosses -> gloss','glosses',1,'p_glosses_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',149),
  ('glosses -> glosses SEMI gloss','glosses',3,'p_glosses_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',153),
  ('gloss -> GTEXT','gloss',1,'p_gloss_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',157),
  ('gloss -> GTEXT taglists','gloss',2,'p_gloss_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',161),
  ('gloss -> taglists GTEXT','gloss',2,'p_gloss_3','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',165),
  ('gloss -> taglists GTEXT taglists','gloss',3,'p_gloss_4','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',169),
  ('taglists -> taglist','taglists',1,'p_taglists_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',173),
  ('taglists -> taglists taglist','taglists',2,'p_taglists_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',177),
  ('taglist -> BRKTL tags BRKTR','taglist',3,'p_taglist_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',182),
  ('tags -> tagitem','tags',1,'p_tags_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',186),
  ('tags -> tags COMMA tagitem','tags',3,'p_tags_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',190),
  ('tagitem -> KTEXT','tagitem',1,'p_tagitem_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',195),
  ('tagitem -> RTEXT','tagitem',1,'p_tagitem_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',199),
  ('tagitem -> TEXT','tagitem',1,'p_tagitem_3','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',203),
  ('tagitem -> QTEXT','tagitem',1,'p_tagitem_4','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',212),
  ('tagitem -> TEXT EQL TEXT','tagitem',3,'p_tagitem_5','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',221),
  ('tagitem -> TEXT EQL TEXT COLON','tagitem',4,'p_tagitem_6','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',225),
  ('tagitem -> TEXT EQL TEXT COLON atext','tagitem',5,'p_tagitem_7','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',233),
  ('tagitem -> TEXT EQL TEXT SLASH TEXT COLON','tagitem',6,'p_tagitem_8','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',247),
  ('tagitem -> TEXT EQL TEXT SLASH TEXT COLON atext','tagitem',7,'p_tagitem_9','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',258),
  ('tagitem -> TEXT EQL jrefs','tagitem',3,'p_tagitem_10','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',269),
  ('atext -> TEXT','atext',1,'p_atext_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',309),
  ('atext -> QTEXT','atext',1,'p_atext_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',313),
  ('jrefs -> jref','jrefs',1,'p_jrefs_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',317),
  ('jrefs -> jrefs SEMI jref','jrefs',3,'p_jrefs_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',321),
  ('jref -> xrefnum','jref',1,'p_jref_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',325),
  ('jref -> xrefnum slist','jref',2,'p_jref_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',329),
  ('jref -> xrefnum DOT jitem','jref',3,'p_jref_3','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',333),
  ('jref -> jitem','jref',1,'p_jref_4','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',337),
  ('jitem -> dotlist','jitem',1,'p_jitem_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',341),
  ('jitem -> dotlist slist','jitem',2,'p_jitem_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',345),
  ('dotlist -> jtext','dotlist',1,'p_dotlist_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',349),
  ('dotlist -> dotlist DOT jtext','dotlist',3,'p_dotlist_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',353),
  ('jtext -> KTEXT','jtext',1,'p_jtext_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',357),
  ('jtext -> RTEXT','jtext',1,'p_jtext_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',361),
  ('jtext -> QTEXT','jtext',1,'p_jtext_3','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',365),
  ('xrefnum -> NUMBER','xrefnum',1,'p_xrefnum_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',369),
  ('xrefnum -> NUMBER HASH','xrefnum',2,'p_xrefnum_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',373),
  ('xrefnum -> NUMBER TEXT','xrefnum',2,'p_xrefnum_3','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',377),
  ('slist -> BRKTL snums BRKTR','slist',3,'p_slist_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',381),
  ('snums -> NUMBER','snums',1,'p_snums_1','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',385),
  ('snums -> snums COMMA NUMBER','snums',3,'p_snums_2','/home/stuart/devel/jdb/jb3/python/lib/jelparse.py',392),
]
