
# jelparse_tab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x95g\xa2q)4\x92\x1e\x87\xf7C\x87\x08\xa5\xc7z'

_lr_action_items = {'SLASH':([48,],[60,]),'SNUM':([12,19,20,28,30,31,32,34,38,39,40,41,42,43,58,59,70,71,],[-24,33,-25,33,33,33,-15,-26,33,33,-16,-18,-17,-20,-21,-22,-19,-23,]),'DOT':([47,49,51,52,53,54,56,68,69,80,],[-49,63,67,-53,-51,-52,-54,-56,-55,-50,]),'GTEXT':([12,20,33,34,44,57,],[-24,-25,43,-26,59,43,]),'HASH':([56,],[69,]),'EQL':([26,],[36,]),'BRKTL':([5,6,7,11,12,16,20,29,33,34,43,44,47,49,51,52,53,54,56,57,58,59,68,69,71,80,],[-13,-14,13,13,-24,13,-25,13,13,-26,13,13,-49,64,64,-53,-51,-52,-54,13,13,13,-56,-55,13,-50,]),'BRKTR':([21,22,23,24,25,26,45,46,47,48,49,50,51,52,53,54,55,56,61,62,66,68,69,73,74,75,76,77,78,79,80,81,83,84,85,],[-30,-32,34,-27,-29,-31,-28,-46,-49,-33,-43,-38,-47,-53,-51,-52,-41,-54,-34,-44,-48,-56,-55,-35,-39,-40,-45,83,-58,-42,-50,-36,-57,-37,-59,]),'COLON':([48,72,],[61,81,]),'QTEXT':([13,35,36,61,63,65,67,81,],[22,22,52,75,52,52,52,75,]),'SEMI':([3,4,5,6,7,11,12,14,15,16,17,18,20,29,34,37,41,42,43,46,47,49,50,51,52,53,54,55,56,58,59,62,66,68,69,70,71,76,79,80,83,],[-5,9,-13,-14,-7,-8,-24,-9,27,-11,-6,27,-25,-12,-26,-10,-18,57,-20,-46,-49,-43,65,-47,-53,-51,-52,-41,-54,-21,-22,-44,-48,-56,-55,-19,-23,-45,-42,-50,-57,]),'COMMA':([21,22,23,24,25,26,45,46,47,48,49,50,51,52,53,54,55,56,61,62,66,68,69,73,74,75,76,77,78,79,80,81,83,84,85,],[-30,-32,35,-27,-29,-31,-28,-46,-49,-33,-43,-38,-47,-53,-51,-52,-41,-54,-34,-44,-48,-56,-55,-35,-39,-40,-45,82,-58,-42,-50,-36,-57,-37,-59,]),'RTEXT':([0,8,9,10,13,27,35,36,63,65,67,],[6,6,6,6,21,6,21,54,54,54,54,]),'KTEXT':([0,8,9,10,13,27,35,36,63,65,67,],[5,5,5,5,25,5,25,53,53,53,53,]),'TEXT':([13,35,36,56,60,61,81,],[26,26,48,68,72,74,74,]),'$end':([1,2,12,20,31,32,34,38,39,40,41,42,43,58,59,70,71,],[0,-1,-24,-25,-4,-15,-26,-3,-2,-16,-18,-17,-20,-21,-22,-19,-23,]),'NL':([0,3,4,5,6,7,10,11,12,14,15,16,17,18,20,29,34,37,],[8,-5,10,-13,-14,-7,19,-8,-24,-9,28,-11,-6,30,-25,-12,-26,-10,]),'NUMBER':([36,64,65,82,],[56,78,56,85,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'rdngitem':([8,10,27,],[14,14,37,]),'entr':([0,],[1,]),'atext':([61,81,],[73,84,]),'gloss':([33,57,],[41,70,]),'dotlist':([36,63,65,],[51,51,51,]),'slist':([49,51,],[62,66,]),'senses':([19,28,30,],[31,38,39,]),'kanjsect':([0,],[4,]),'xrefnum':([36,65,],[49,49,]),'taglist':([7,11,16,29,33,43,44,57,58,59,71,],[12,20,12,20,12,12,20,12,20,12,20,]),'tagitem':([13,35,],[24,45,]),'preentr':([0,],[2,]),'krtext':([0,8,9,10,27,],[7,16,7,16,16,]),'jref':([36,65,],[55,79,]),'jitem':([36,63,65,],[46,76,46,]),'taglists':([7,16,33,43,57,59,],[11,29,44,58,44,71,]),'glosses':([33,],[42,]),'jtext':([36,63,65,67,],[47,47,47,80,]),'rdngsect':([8,10,],[15,18,]),'sense':([19,28,30,31,38,39,],[32,32,32,40,40,40,]),'kanjitem':([0,9,],[3,17,]),'snums':([64,],[77,]),'jrefs':([36,],[50,]),'tags':([13,],[23,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> entr","S'",1,None,None,None),
  ('entr -> preentr','entr',1,'p_entr_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',40),
  ('preentr -> kanjsect NL rdngsect NL senses','preentr',5,'p_preentr_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',76),
  ('preentr -> NL rdngsect NL senses','preentr',4,'p_preentr_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',80),
  ('preentr -> kanjsect NL NL senses','preentr',4,'p_preentr_3','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',84),
  ('kanjsect -> kanjitem','kanjsect',1,'p_kanjsect_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',88),
  ('kanjsect -> kanjsect SEMI kanjitem','kanjsect',3,'p_kanjsect_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',92),
  ('kanjitem -> krtext','kanjitem',1,'p_kanjitem_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',96),
  ('kanjitem -> krtext taglists','kanjitem',2,'p_kanjitem_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',100),
  ('rdngsect -> rdngitem','rdngsect',1,'p_rdngsect_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',107),
  ('rdngsect -> rdngsect SEMI rdngitem','rdngsect',3,'p_rdngsect_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',111),
  ('rdngitem -> krtext','rdngitem',1,'p_rdngitem_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',115),
  ('rdngitem -> krtext taglists','rdngitem',2,'p_rdngitem_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',119),
  ('krtext -> KTEXT','krtext',1,'p_krtext_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',126),
  ('krtext -> RTEXT','krtext',1,'p_krtext_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',130),
  ('senses -> sense','senses',1,'p_senses_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',134),
  ('senses -> senses sense','senses',2,'p_senses_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',138),
  ('sense -> SNUM glosses','sense',2,'p_sense_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',146),
  ('glosses -> gloss','glosses',1,'p_glosses_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',158),
  ('glosses -> glosses SEMI gloss','glosses',3,'p_glosses_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',162),
  ('gloss -> GTEXT','gloss',1,'p_gloss_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',166),
  ('gloss -> GTEXT taglists','gloss',2,'p_gloss_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',170),
  ('gloss -> taglists GTEXT','gloss',2,'p_gloss_3','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',174),
  ('gloss -> taglists GTEXT taglists','gloss',3,'p_gloss_4','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',178),
  ('taglists -> taglist','taglists',1,'p_taglists_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',182),
  ('taglists -> taglists taglist','taglists',2,'p_taglists_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',186),
  ('taglist -> BRKTL tags BRKTR','taglist',3,'p_taglist_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',191),
  ('tags -> tagitem','tags',1,'p_tags_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',195),
  ('tags -> tags COMMA tagitem','tags',3,'p_tags_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',199),
  ('tagitem -> KTEXT','tagitem',1,'p_tagitem_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',204),
  ('tagitem -> RTEXT','tagitem',1,'p_tagitem_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',208),
  ('tagitem -> TEXT','tagitem',1,'p_tagitem_3','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',212),
  ('tagitem -> QTEXT','tagitem',1,'p_tagitem_4','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',221),
  ('tagitem -> TEXT EQL TEXT','tagitem',3,'p_tagitem_5','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',230),
  ('tagitem -> TEXT EQL TEXT COLON','tagitem',4,'p_tagitem_6','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',234),
  ('tagitem -> TEXT EQL TEXT COLON atext','tagitem',5,'p_tagitem_7','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',242),
  ('tagitem -> TEXT EQL TEXT SLASH TEXT COLON','tagitem',6,'p_tagitem_8','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',256),
  ('tagitem -> TEXT EQL TEXT SLASH TEXT COLON atext','tagitem',7,'p_tagitem_9','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',267),
  ('tagitem -> TEXT EQL jrefs','tagitem',3,'p_tagitem_10','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',278),
  ('atext -> TEXT','atext',1,'p_atext_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',318),
  ('atext -> QTEXT','atext',1,'p_atext_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',322),
  ('jrefs -> jref','jrefs',1,'p_jrefs_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',326),
  ('jrefs -> jrefs SEMI jref','jrefs',3,'p_jrefs_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',330),
  ('jref -> xrefnum','jref',1,'p_jref_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',334),
  ('jref -> xrefnum slist','jref',2,'p_jref_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',338),
  ('jref -> xrefnum DOT jitem','jref',3,'p_jref_3','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',342),
  ('jref -> jitem','jref',1,'p_jref_4','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',346),
  ('jitem -> dotlist','jitem',1,'p_jitem_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',350),
  ('jitem -> dotlist slist','jitem',2,'p_jitem_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',354),
  ('dotlist -> jtext','dotlist',1,'p_dotlist_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',358),
  ('dotlist -> dotlist DOT jtext','dotlist',3,'p_dotlist_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',362),
  ('jtext -> KTEXT','jtext',1,'p_jtext_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',366),
  ('jtext -> RTEXT','jtext',1,'p_jtext_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',370),
  ('jtext -> QTEXT','jtext',1,'p_jtext_3','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',374),
  ('xrefnum -> NUMBER','xrefnum',1,'p_xrefnum_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',378),
  ('xrefnum -> NUMBER HASH','xrefnum',2,'p_xrefnum_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',382),
  ('xrefnum -> NUMBER TEXT','xrefnum',2,'p_xrefnum_3','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',386),
  ('slist -> BRKTL snums BRKTR','slist',3,'p_slist_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',390),
  ('snums -> NUMBER','snums',1,'p_snums_1','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',394),
  ('snums -> snums COMMA NUMBER','snums',3,'p_snums_2','/home/stuart/devel/jdb/jbsens/python/lib/jelparse.py',401),
]
