
# jelparse_tab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x95g\xa2q)4\x92\x1e\x87\xf7C\x87\x08\xa5\xc7z'

_lr_action_items = {'NUMBER':([34,60,65,83,],[49,49,77,85,]),'KTEXT':([0,8,9,10,11,28,34,36,60,66,68,],[3,3,3,3,20,3,53,20,53,53,53,]),'SLASH':([48,],[61,]),'TEXT':([11,34,36,49,61,62,81,],[21,48,21,63,73,75,75,]),'RTEXT':([0,8,9,10,11,28,34,36,60,66,68,],[4,4,4,4,22,4,55,22,55,55,55,]),'BRKTR':([20,21,22,23,24,25,45,46,47,48,49,50,51,52,53,54,55,56,62,63,64,67,69,72,74,75,76,77,78,79,80,81,82,84,85,],[-29,-31,-30,35,-27,-32,-38,-41,-49,-33,-54,-46,-43,-47,-51,-53,-52,-28,-34,-56,-55,-44,-48,-42,-35,-39,-40,-58,82,-45,-50,-36,-57,-37,-59,]),'GTEXT':([12,26,32,35,40,58,],[-24,-25,43,-26,57,43,]),'BRKTL':([2,3,4,12,13,14,26,27,32,35,40,43,47,49,51,52,53,54,55,57,58,59,63,64,70,80,],[11,-13,-14,-24,11,11,-25,11,11,-26,11,11,-49,-54,65,65,-51,-53,-52,11,11,11,-56,-55,11,-50,]),'EQL':([21,],[34,]),'$end':([5,7,12,26,30,31,35,38,39,41,42,43,44,57,59,70,71,],[0,-1,-24,-25,-4,-15,-26,-3,-16,-18,-17,-20,-2,-22,-21,-23,-19,]),'SEMI':([1,2,3,4,6,12,13,14,15,16,17,19,26,27,35,37,41,42,43,45,46,47,49,50,51,52,53,54,55,57,59,63,64,67,69,70,71,72,79,80,82,],[9,-7,-13,-14,-5,-24,-8,-11,-9,28,-6,28,-25,-12,-26,-10,-18,58,-20,60,-41,-49,-54,-46,-43,-47,-51,-53,-52,-22,-21,-56,-55,-44,-48,-23,-19,-42,-45,-50,-57,]),'DOT':([47,49,51,52,53,54,55,63,64,80,],[-49,-54,66,68,-51,-53,-52,-56,-55,-50,]),'COMMA':([20,21,22,23,24,25,45,46,47,48,49,50,51,52,53,54,55,56,62,63,64,67,69,72,74,75,76,77,78,79,80,81,82,84,85,],[-29,-31,-30,36,-27,-32,-38,-41,-49,-33,-54,-46,-43,-47,-51,-53,-52,-28,-34,-56,-55,-44,-48,-42,-35,-39,-40,-58,83,-45,-50,-36,-57,-37,-59,]),'QTEXT':([11,34,36,60,62,66,68,81,],[25,54,25,54,76,54,54,76,]),'NL':([0,1,2,3,4,6,10,12,13,14,15,16,17,19,26,27,35,37,],[8,10,-7,-13,-14,-5,18,-24,-8,-11,-9,29,-6,33,-25,-12,-26,-10,]),'SNUM':([12,18,26,29,30,31,33,35,38,39,41,42,43,44,57,59,70,71,],[-24,32,-25,32,32,-15,32,-26,32,-16,-18,-17,-20,32,-22,-21,-23,-19,]),'COLON':([48,73,],[62,81,]),'HASH':([49,],[64,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'jref':([34,60,],[46,72,]),'jrefs':([34,],[45,]),'jitem':([34,60,66,],[50,50,79,]),'senses':([18,29,33,],[30,38,44,]),'entr':([0,],[5,]),'xrefnum':([34,60,],[51,51,]),'slist':([51,52,],[67,69,]),'jtext':([34,60,66,68,],[47,47,47,80,]),'taglists':([2,14,32,43,57,58,],[13,27,40,59,70,40,]),'kanjsect':([0,],[1,]),'krtext':([0,8,9,10,28,],[2,14,2,14,14,]),'dotlist':([34,60,66,],[52,52,52,]),'snums':([65,],[78,]),'taglist':([2,13,14,27,32,40,43,57,58,59,70,],[12,26,12,26,12,26,12,12,12,26,26,]),'gloss':([32,58,],[41,71,]),'atext':([62,81,],[74,84,]),'rdngsect':([8,10,],[16,19,]),'tags':([11,],[23,]),'tagitem':([11,36,],[24,56,]),'kanjitem':([0,9,],[6,17,]),'sense':([18,29,30,33,38,44,],[31,31,39,31,39,39,]),'rdngitem':([8,10,28,],[15,15,37,]),'glosses':([32,],[42,]),'preentr':([0,],[7,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> entr","S'",1,None,None,None),
  ('entr -> preentr','entr',1,'p_entr_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',40),
  ('preentr -> kanjsect NL rdngsect NL senses','preentr',5,'p_preentr_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',76),
  ('preentr -> NL rdngsect NL senses','preentr',4,'p_preentr_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',80),
  ('preentr -> kanjsect NL NL senses','preentr',4,'p_preentr_3','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',84),
  ('kanjsect -> kanjitem','kanjsect',1,'p_kanjsect_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',88),
  ('kanjsect -> kanjsect SEMI kanjitem','kanjsect',3,'p_kanjsect_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',92),
  ('kanjitem -> krtext','kanjitem',1,'p_kanjitem_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',96),
  ('kanjitem -> krtext taglists','kanjitem',2,'p_kanjitem_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',100),
  ('rdngsect -> rdngitem','rdngsect',1,'p_rdngsect_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',107),
  ('rdngsect -> rdngsect SEMI rdngitem','rdngsect',3,'p_rdngsect_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',111),
  ('rdngitem -> krtext','rdngitem',1,'p_rdngitem_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',115),
  ('rdngitem -> krtext taglists','rdngitem',2,'p_rdngitem_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',119),
  ('krtext -> KTEXT','krtext',1,'p_krtext_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',126),
  ('krtext -> RTEXT','krtext',1,'p_krtext_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',130),
  ('senses -> sense','senses',1,'p_senses_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',134),
  ('senses -> senses sense','senses',2,'p_senses_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',138),
  ('sense -> SNUM glosses','sense',2,'p_sense_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',146),
  ('glosses -> gloss','glosses',1,'p_glosses_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',156),
  ('glosses -> glosses SEMI gloss','glosses',3,'p_glosses_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',160),
  ('gloss -> GTEXT','gloss',1,'p_gloss_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',164),
  ('gloss -> GTEXT taglists','gloss',2,'p_gloss_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',168),
  ('gloss -> taglists GTEXT','gloss',2,'p_gloss_3','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',172),
  ('gloss -> taglists GTEXT taglists','gloss',3,'p_gloss_4','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',176),
  ('taglists -> taglist','taglists',1,'p_taglists_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',180),
  ('taglists -> taglists taglist','taglists',2,'p_taglists_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',184),
  ('taglist -> BRKTL tags BRKTR','taglist',3,'p_taglist_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',189),
  ('tags -> tagitem','tags',1,'p_tags_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',193),
  ('tags -> tags COMMA tagitem','tags',3,'p_tags_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',197),
  ('tagitem -> KTEXT','tagitem',1,'p_tagitem_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',202),
  ('tagitem -> RTEXT','tagitem',1,'p_tagitem_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',206),
  ('tagitem -> TEXT','tagitem',1,'p_tagitem_3','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',210),
  ('tagitem -> QTEXT','tagitem',1,'p_tagitem_4','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',219),
  ('tagitem -> TEXT EQL TEXT','tagitem',3,'p_tagitem_5','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',228),
  ('tagitem -> TEXT EQL TEXT COLON','tagitem',4,'p_tagitem_6','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',232),
  ('tagitem -> TEXT EQL TEXT COLON atext','tagitem',5,'p_tagitem_7','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',240),
  ('tagitem -> TEXT EQL TEXT SLASH TEXT COLON','tagitem',6,'p_tagitem_8','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',254),
  ('tagitem -> TEXT EQL TEXT SLASH TEXT COLON atext','tagitem',7,'p_tagitem_9','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',265),
  ('tagitem -> TEXT EQL jrefs','tagitem',3,'p_tagitem_10','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',276),
  ('atext -> TEXT','atext',1,'p_atext_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',316),
  ('atext -> QTEXT','atext',1,'p_atext_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',320),
  ('jrefs -> jref','jrefs',1,'p_jrefs_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',324),
  ('jrefs -> jrefs SEMI jref','jrefs',3,'p_jrefs_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',328),
  ('jref -> xrefnum','jref',1,'p_jref_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',332),
  ('jref -> xrefnum slist','jref',2,'p_jref_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',336),
  ('jref -> xrefnum DOT jitem','jref',3,'p_jref_3','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',340),
  ('jref -> jitem','jref',1,'p_jref_4','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',344),
  ('jitem -> dotlist','jitem',1,'p_jitem_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',348),
  ('jitem -> dotlist slist','jitem',2,'p_jitem_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',352),
  ('dotlist -> jtext','dotlist',1,'p_dotlist_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',356),
  ('dotlist -> dotlist DOT jtext','dotlist',3,'p_dotlist_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',360),
  ('jtext -> KTEXT','jtext',1,'p_jtext_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',364),
  ('jtext -> RTEXT','jtext',1,'p_jtext_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',368),
  ('jtext -> QTEXT','jtext',1,'p_jtext_3','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',372),
  ('xrefnum -> NUMBER','xrefnum',1,'p_xrefnum_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',376),
  ('xrefnum -> NUMBER HASH','xrefnum',2,'p_xrefnum_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',380),
  ('xrefnum -> NUMBER TEXT','xrefnum',2,'p_xrefnum_3','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',384),
  ('slist -> BRKTL snums BRKTR','slist',3,'p_slist_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',388),
  ('snums -> NUMBER','snums',1,'p_snums_1','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',392),
  ('snums -> snums COMMA NUMBER','snums',3,'p_snums_2','/home/stuart/devel/jdb/jb/python/lib/jelparse.py',399),
]
