# This file was generated by mkkwmod.py-b276fc3199af on Fri May  2 11:14:22 2008

import jdb

KW = jdb.Kwds()
KW.add ("CINF", (1, r'nelson_c', '"""Modern Reader\'s Japanese-English Character Dictionary"", edited by Andrew Nelson (now published as the ""Classic"" Nelson)."'))
KW.add ("CINF", (2, r'nelson_n', '"""The New Nelson Japanese-English Character Dictionary"", edited by John Haig."'))
KW.add ("CINF", (3, r'halpern_njecd', '"""New Japanese-English Character Dictionary"", edited by Jack Halpern."'))
KW.add ("CINF", (4, r'halpern_kkld', '"""Kanji Learners Dictionary"" (Kodansha) edited by Jack Halpern."'))
KW.add ("CINF", (5, r'heisig', '"""Remembering The  Kanji""  by  James Heisig."'))
KW.add ("CINF", (6, r'gakken', '"""A  New Dictionary of Kanji Usage"" (Gakken)."'))
KW.add ("CINF", (7, r'oneill_names', '"""Japanese Names"", by P.G. O\'Neill."'))
KW.add ("CINF", (8, r'oneill_kk', '"""Essential Kanji"" by P.G. O\'Neill."'))
KW.add ("CINF", (9, r'moro', '"""Daikanwajiten"" compiled by Morohashi."'))
KW.add ("CINF", (10, r'henshall', '"""A Guide To Remembering Japanese Characters"" by Kenneth G.  Henshall."'))
KW.add ("CINF", (11, r'sh_kk', '"""Kanji and Kana"" by Spahn and Hadamitzky."'))
KW.add ("CINF", (12, r'sakade', '"""A Guide To Reading and Writing Japanese"" edited by Florence Sakade."'))
KW.add ("CINF", (13, r'tutt_cards', 'Tuttle Kanji Cards, compiled by Alexander Kask.'))
KW.add ("CINF", (14, r'crowley', '"""The Kanji Way to Japanese Language Power"" by Dale Crowley."'))
KW.add ("CINF", (15, r'kanji_in_ctx', '"""Kanji in Context"" by Nishiguchi and Kono."'))
KW.add ("CINF", (16, r'busy_people', '"""Japanese For Busy People"" vols I-III, published by the AJLT. The codes are the volume.chapter."'))
KW.add ("CINF", (17, r'kodansha_comp', '"The ""Kodansha Compact Kanji Guide""."'))
KW.add ("CINF", (18, r'skip', "Halpern's SKIP (System  of  Kanji  Indexing  by  Patterns) code."))
KW.add ("CINF", (21, r'deroo', '"Codes developed by the late Father Joseph De Roo, and published in  his book ""2001 Kanji"" (Bojinsha)."'))
KW.add ("CINF", (22, r'misclass', 'A possible misclassification of the kanji according to one of the code types.'))
KW.add ("CINF", (23, r'pinyin', 'Modern PinYin romanization of the Chinese reading.'))
KW.add ("CINF", (24, r'strokes', 'Stroke miscount or alternate count.'))
KW.add ("CINF", (25, r'jis208', 'JIS X 0208-1997 - kuten coding (nn-nn).'))
KW.add ("CINF", (26, r'jis212', 'JIS X 0212-1990 - kuten coding (nn-nn).'))
KW.add ("CINF", (27, r'jis213', 'JIS X 0213-2000 - kuten coding (p-nn-nn).'))
KW.add ("CINF", (28, r'henshall3', '"""A Guide To Reading and Writing Japanese"" 3rd edition, edited by Henshall, Seeley and De Groot."'))
KW.add ("CINF", (29, r'korean_h', 'Korean reading of the kanji in hangul.'))
KW.add ("CINF", (30, r'korean_r', 'Romanized form of the Korean reading of the kanji.'))
KW.add ("CINF", (31, r'jf_cards', 'Japanese Kanji Flashcards, by Max Hodges and Tomoko Okazaki.'))
KW.add ("CINF", (32, r'nelson_rad', 'Radical number given in nelson_c.'))
KW.add ("CINF", (33, r'skip_mis', 'SKIP code misclasification.'))
KW.add ("CINF", (34, r's_h', '"""The Kanji Dictionary"" by Spahn and Hadamitzky."'))
KW.add ("CINF", (19, r'sh_desc', 'Descriptor codes for The Kanji Dictionary (Tuttle 1996) by Spahn and Hadamitzky.'))
KW.add ("CINF", (20, r'four_corner', '"""Four Corner"" code for the kanji invented by Wang Chen in 1928."'))
KW.add ("DIAL", (1, r'std', 'Tokyo-ben (std)'))
KW.add ("DIAL", (2, r'ksb', 'Kansai-ben'))
KW.add ("DIAL", (3, r'ktb', 'Kantou-ben'))
KW.add ("DIAL", (4, r'kyb', 'Kyoto-ben'))
KW.add ("DIAL", (5, r'osb', 'Osaka-ben'))
KW.add ("DIAL", (6, r'tsb', 'Tosa-ben'))
KW.add ("DIAL", (7, r'thb', 'Touhoku-ben'))
KW.add ("DIAL", (8, r'tsug', 'Tsugaru-ben'))
KW.add ("DIAL", (10, r'rkb', 'Ryuukyuu-ben'))
KW.add ("DIAL", (9, r'kyu', 'Kyuushuu-ben'))
KW.add ("FLD", (1, r'Buddh', 'Buddhist term'))
KW.add ("FLD", (2, r'comp', 'computer terminology'))
KW.add ("FLD", (3, r'food', 'food term'))
KW.add ("FLD", (4, r'geom', 'geometry term'))
KW.add ("FLD", (5, r'ling', 'linguistics terminology'))
KW.add ("FLD", (6, r'MA', 'martial arts term'))
KW.add ("FLD", (7, r'math', 'mathematics'))
KW.add ("FLD", (8, r'mil', 'military'))
KW.add ("FLD", (9, r'physics', 'physics terminology'))
KW.add ("FREQ", (1, r'ichi', 'Ranking from "Ichimango goi bunruishuu", 1-2.'))
KW.add ("FREQ", (2, r'gai', 'Common loanwords based on wordfreq file, 1-2'))
KW.add ("FREQ", (4, r'spec', 'Ranking assigned by JMdict editors, 1-2'))
KW.add ("FREQ", (5, r'nf', 'Ranking in wordfreq file, 1-48'))
KW.add ("FREQ", (6, r'gA', 'Google counts (by Kale Stutzman, 2007-01-14)'))
KW.add ("FREQ", (7, r'news', 'Ranking in wordfreq file, 1-2'))
KW.add ("GINF", (1, r'equ', 'equivalent'))
KW.add ("GINF", (2, r'lit', 'literaly'))
KW.add ("GINF", (3, r'id', 'idiomatically'))
KW.add ("GINF", (4, r'expl', 'explanatory'))
KW.add ("KINF", (1, r'iK', 'word containing irregular kanji usage'))
KW.add ("KINF", (2, r'io', 'irregular okurigana usage'))
KW.add ("KINF", (3, r'oK', 'word containing out-dated kanji'))
KW.add ("KINF", (5, r'ateji', 'ateji (phonetic) reading'))
KW.add ("KINF", (4, r'ik', 'word containing irregular kana usage'))
KW.add ("LANG", (1, r'eng', 'English'))
KW.add ("LANG", (2, r'abk', 'Abkhazian'))
KW.add ("LANG", (3, r'ace', 'Achinese'))
KW.add ("LANG", (4, r'ach', 'Acoli'))
KW.add ("LANG", (5, r'ada', 'Adangme'))
KW.add ("LANG", (6, r'ady', 'Adyghe; Adygei'))
KW.add ("LANG", (7, r'afa', 'Afro-Asiatic (Other)'))
KW.add ("LANG", (8, r'afh', 'Afrihili'))
KW.add ("LANG", (9, r'afr', 'Afrikaans'))
KW.add ("LANG", (10, r'ain', 'Ainu'))
KW.add ("LANG", (11, r'aka', 'Akan'))
KW.add ("LANG", (12, r'akk', 'Akkadian'))
KW.add ("LANG", (13, r'alb', 'Albanian'))
KW.add ("LANG", (14, r'ale', 'Aleut'))
KW.add ("LANG", (15, r'alg', 'Algonquian languages'))
KW.add ("LANG", (16, r'alt', 'Southern Altai'))
KW.add ("LANG", (17, r'amh', 'Amharic'))
KW.add ("LANG", (18, r'ang', 'English, Old (ca.450-1100)'))
KW.add ("LANG", (19, r'anp', 'Angika'))
KW.add ("LANG", (20, r'apa', 'Apache languages'))
KW.add ("LANG", (21, r'ara', 'Arabic'))
KW.add ("LANG", (22, r'arc', 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)'))
KW.add ("LANG", (23, r'arg', 'Aragonese'))
KW.add ("LANG", (24, r'arm', 'Armenian'))
KW.add ("LANG", (25, r'arn', 'Mapudungun; Mapuche'))
KW.add ("LANG", (27, r'art', 'Artificial (Other)'))
KW.add ("LANG", (28, r'arw', 'Arawak'))
KW.add ("LANG", (29, r'asm', 'Assamese'))
KW.add ("LANG", (30, r'ast', 'Asturian; Bable; Leonese; Asturleonese'))
KW.add ("LANG", (31, r'ath', 'Athapascan languages'))
KW.add ("LANG", (32, r'aus', 'Australian languages'))
KW.add ("LANG", (33, r'ava', 'Avaric'))
KW.add ("LANG", (34, r'ave', 'Avestan'))
KW.add ("LANG", (35, r'awa', 'Awadhi'))
KW.add ("LANG", (36, r'aym', 'Aymara'))
KW.add ("LANG", (37, r'aze', 'Azerbaijani'))
KW.add ("LANG", (38, r'bad', 'Banda languages'))
KW.add ("LANG", (39, r'bai', 'Bamileke languages'))
KW.add ("LANG", (40, r'bak', 'Bashkir'))
KW.add ("LANG", (41, r'bal', 'Baluchi'))
KW.add ("LANG", (42, r'bam', 'Bambara'))
KW.add ("LANG", (43, r'ban', 'Balinese'))
KW.add ("LANG", (44, r'baq', 'Basque'))
KW.add ("LANG", (45, r'bas', 'Basa'))
KW.add ("LANG", (46, r'bat', 'Baltic (Other)'))
KW.add ("LANG", (47, r'bej', 'Beja; Bedawiyet'))
KW.add ("LANG", (48, r'bel', 'Belarusian'))
KW.add ("LANG", (49, r'bem', 'Bemba'))
KW.add ("LANG", (51, r'ber', 'Berber (Other)'))
KW.add ("LANG", (52, r'bho', 'Bhojpuri'))
KW.add ("LANG", (53, r'bih', 'Bihari'))
KW.add ("LANG", (54, r'bik', 'Bikol'))
KW.add ("LANG", (56, r'bis', 'Bislama'))
KW.add ("LANG", (57, r'bla', 'Siksika'))
KW.add ("LANG", (58, r'bnt', 'Bantu (Other)'))
KW.add ("LANG", (59, r'bos', 'Bosnian'))
KW.add ("LANG", (60, r'bra', 'Braj'))
KW.add ("LANG", (61, r'bre', 'Breton'))
KW.add ("LANG", (62, r'btk', 'Batak languages'))
KW.add ("LANG", (63, r'bua', 'Buriat'))
KW.add ("LANG", (64, r'bug', 'Buginese'))
KW.add ("LANG", (65, r'bul', 'Bulgarian'))
KW.add ("LANG", (66, r'bur', 'Burmese'))
KW.add ("LANG", (68, r'cad', 'Caddo'))
KW.add ("LANG", (69, r'cai', 'Central American Indian (Other)'))
KW.add ("LANG", (70, r'car', 'Galibi Carib'))
KW.add ("LANG", (71, r'cat', 'Catalan; Valencian'))
KW.add ("LANG", (72, r'cau', 'Caucasian (Other)'))
KW.add ("LANG", (74, r'cel', 'Celtic (Other)'))
KW.add ("LANG", (75, r'cha', 'Chamorro'))
KW.add ("LANG", (76, r'chb', 'Chibcha'))
KW.add ("LANG", (77, r'che', 'Chechen'))
KW.add ("LANG", (78, r'chg', 'Chagatai'))
KW.add ("LANG", (79, r'chi', 'Chinese'))
KW.add ("LANG", (80, r'chk', 'Chuukese'))
KW.add ("LANG", (81, r'chm', 'Mari'))
KW.add ("LANG", (82, r'chn', 'Chinook jargon'))
KW.add ("LANG", (83, r'cho', 'Choctaw'))
KW.add ("LANG", (84, r'chp', 'Chipewyan; Dene Suline'))
KW.add ("LANG", (85, r'chr', 'Cherokee'))
KW.add ("LANG", (86, r'chu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'))
KW.add ("LANG", (87, r'chv', 'Chuvash'))
KW.add ("LANG", (88, r'chy', 'Cheyenne'))
KW.add ("LANG", (89, r'cmc', 'Chamic languages'))
KW.add ("LANG", (90, r'cop', 'Coptic'))
KW.add ("LANG", (91, r'cor', 'Cornish'))
KW.add ("LANG", (92, r'cos', 'Corsican'))
KW.add ("LANG", (93, r'cpe', 'Creoles and pidgins, English based (Other)'))
KW.add ("LANG", (94, r'cpf', 'Creoles and pidgins, French-based (Other)'))
KW.add ("LANG", (95, r'cpp', 'Creoles and pidgins, Portuguese-based (Other)'))
KW.add ("LANG", (96, r'cre', 'Cree'))
KW.add ("LANG", (97, r'crh', 'Crimean Tatar; Crimean Turkish'))
KW.add ("LANG", (98, r'crp', 'Creoles and pidgins (Other)'))
KW.add ("LANG", (99, r'csb', 'Kashubian'))
KW.add ("LANG", (100, r'cus', 'Cushitic (Other)'))
KW.add ("LANG", (101, r'cze', 'Czech'))
KW.add ("LANG", (102, r'dak', 'Dakota'))
KW.add ("LANG", (103, r'dan', 'Danish'))
KW.add ("LANG", (104, r'dar', 'Dargwa'))
KW.add ("LANG", (105, r'day', 'Land Dayak languages'))
KW.add ("LANG", (106, r'del', 'Delaware'))
KW.add ("LANG", (107, r'den', 'Slave (Athapascan)'))
KW.add ("LANG", (109, r'din', 'Dinka'))
KW.add ("LANG", (110, r'div', 'Divehi; Dhivehi; Maldivian'))
KW.add ("LANG", (111, r'doi', 'Dogri'))
KW.add ("LANG", (112, r'dra', 'Dravidian (Other)'))
KW.add ("LANG", (113, r'dsb', 'Lower Sorbian'))
KW.add ("LANG", (114, r'dua', 'Duala'))
KW.add ("LANG", (115, r'dum', 'Dutch, Middle (ca.1050-1350)'))
KW.add ("LANG", (116, r'dut', 'Dutch; Flemish'))
KW.add ("LANG", (117, r'dyu', 'Dyula'))
KW.add ("LANG", (118, r'dzo', 'Dzongkha'))
KW.add ("LANG", (119, r'efi', 'Efik'))
KW.add ("LANG", (120, r'egy', 'Egyptian (Ancient)'))
KW.add ("LANG", (121, r'eka', 'Ekajuk'))
KW.add ("LANG", (124, r'enm', 'English, Middle (1100-1500)'))
KW.add ("LANG", (125, r'epo', 'Esperanto'))
KW.add ("LANG", (126, r'est', 'Estonian'))
KW.add ("LANG", (127, r'ewe', 'Ewe'))
KW.add ("LANG", (128, r'ewo', 'Ewondo'))
KW.add ("LANG", (129, r'fan', 'Fang'))
KW.add ("LANG", (130, r'fao', 'Faroese'))
KW.add ("LANG", (131, r'fat', 'Fanti'))
KW.add ("LANG", (132, r'fij', 'Fijian'))
KW.add ("LANG", (133, r'fil', 'Filipino; Pilipino'))
KW.add ("LANG", (134, r'fin', 'Finnish'))
KW.add ("LANG", (135, r'fiu', 'Finno-Ugrian (Other)'))
KW.add ("LANG", (136, r'fon', 'Fon'))
KW.add ("LANG", (137, r'fre', 'French'))
KW.add ("LANG", (138, r'frm', 'French, Middle (ca.1400-1600)'))
KW.add ("LANG", (139, r'fro', 'French, Old (842-ca.1400)'))
KW.add ("LANG", (140, r'frr', 'Northern Frisian'))
KW.add ("LANG", (141, r'frs', 'Eastern Frisian'))
KW.add ("LANG", (142, r'fry', 'Western Frisian'))
KW.add ("LANG", (143, r'ful', 'Fulah'))
KW.add ("LANG", (144, r'fur', 'Friulian'))
KW.add ("LANG", (145, r'gaa', 'Ga'))
KW.add ("LANG", (146, r'gay', 'Gayo'))
KW.add ("LANG", (147, r'gba', 'Gbaya'))
KW.add ("LANG", (148, r'gem', 'Germanic (Other)'))
KW.add ("LANG", (149, r'geo', 'Georgian'))
KW.add ("LANG", (150, r'ger', 'German'))
KW.add ("LANG", (151, r'gez', 'Geez'))
KW.add ("LANG", (152, r'gil', 'Gilbertese'))
KW.add ("LANG", (153, r'gla', 'Gaelic; Scottish Gaelic'))
KW.add ("LANG", (154, r'gle', 'Irish'))
KW.add ("LANG", (155, r'glg', 'Galician'))
KW.add ("LANG", (156, r'glv', 'Manx'))
KW.add ("LANG", (157, r'gmh', 'German, Middle High (ca.1050-1500)'))
KW.add ("LANG", (158, r'goh', 'German, Old High (ca.750-1050)'))
KW.add ("LANG", (159, r'gon', 'Gondi'))
KW.add ("LANG", (160, r'gor', 'Gorontalo'))
KW.add ("LANG", (161, r'got', 'Gothic'))
KW.add ("LANG", (162, r'grb', 'Grebo'))
KW.add ("LANG", (163, r'grc', 'Greek, Ancient (to 1453)'))
KW.add ("LANG", (164, r'gre', 'Greek, Modern (1453-)'))
KW.add ("LANG", (165, r'grn', 'Guarani'))
KW.add ("LANG", (166, r'gsw', 'Swiss German; Alemannic; Alsatian'))
KW.add ("LANG", (167, r'guj', 'Gujarati'))
KW.add ("LANG", (168, r'gwi', "Gwich'in"))
KW.add ("LANG", (169, r'hai', 'Haida'))
KW.add ("LANG", (170, r'hat', 'Haitian; Haitian Creole'))
KW.add ("LANG", (172, r'haw', 'Hawaiian'))
KW.add ("LANG", (173, r'heb', 'Hebrew'))
KW.add ("LANG", (174, r'her', 'Herero'))
KW.add ("LANG", (175, r'hil', 'Hiligaynon'))
KW.add ("LANG", (176, r'him', 'Himachali'))
KW.add ("LANG", (177, r'hin', 'Hindi'))
KW.add ("LANG", (178, r'hit', 'Hittite'))
KW.add ("LANG", (179, r'hmn', 'Hmong'))
KW.add ("LANG", (180, r'hmo', 'Hiri Motu'))
KW.add ("LANG", (181, r'hsb', 'Upper Sorbian'))
KW.add ("LANG", (182, r'hun', 'Hungarian'))
KW.add ("LANG", (183, r'hup', 'Hupa'))
KW.add ("LANG", (184, r'iba', 'Iban'))
KW.add ("LANG", (185, r'ibo', 'Igbo'))
KW.add ("LANG", (186, r'ice', 'Icelandic'))
KW.add ("LANG", (187, r'ido', 'Ido'))
KW.add ("LANG", (188, r'iii', 'Sichuan Yi; Nuosu'))
KW.add ("LANG", (189, r'ijo', 'Ijo languages'))
KW.add ("LANG", (190, r'iku', 'Inuktitut'))
KW.add ("LANG", (191, r'ile', 'Interlingue; Occidental'))
KW.add ("LANG", (192, r'ilo', 'Iloko'))
KW.add ("LANG", (193, r'ina', 'Interlingua (International Auxiliary Language Association)'))
KW.add ("LANG", (194, r'inc', 'Indic (Other)'))
KW.add ("LANG", (195, r'ind', 'Indonesian'))
KW.add ("LANG", (196, r'ine', 'Indo-European (Other)'))
KW.add ("LANG", (197, r'inh', 'Ingush'))
KW.add ("LANG", (198, r'ipk', 'Inupiaq'))
KW.add ("LANG", (199, r'ira', 'Iranian (Other)'))
KW.add ("LANG", (200, r'iro', 'Iroquoian languages'))
KW.add ("LANG", (201, r'ita', 'Italian'))
KW.add ("LANG", (202, r'jav', 'Javanese'))
KW.add ("LANG", (203, r'jbo', 'Lojban'))
KW.add ("LANG", (204, r'jpn', 'Japanese'))
KW.add ("LANG", (205, r'jpr', 'Judeo-Persian'))
KW.add ("LANG", (206, r'jrb', 'Judeo-Arabic'))
KW.add ("LANG", (207, r'kaa', 'Kara-Kalpak'))
KW.add ("LANG", (208, r'kab', 'Kabyle'))
KW.add ("LANG", (209, r'kac', 'Kachin; Jingpho'))
KW.add ("LANG", (210, r'kal', 'Kalaallisut; Greenlandic'))
KW.add ("LANG", (211, r'kam', 'Kamba'))
KW.add ("LANG", (212, r'kan', 'Kannada'))
KW.add ("LANG", (213, r'kar', 'Karen languages'))
KW.add ("LANG", (214, r'kas', 'Kashmiri'))
KW.add ("LANG", (215, r'kau', 'Kanuri'))
KW.add ("LANG", (216, r'kaw', 'Kawi'))
KW.add ("LANG", (217, r'kaz', 'Kazakh'))
KW.add ("LANG", (218, r'kbd', 'Kabardian'))
KW.add ("LANG", (219, r'kha', 'Khasi'))
KW.add ("LANG", (220, r'khi', 'Khoisan (Other)'))
KW.add ("LANG", (221, r'khm', 'Central Khmer'))
KW.add ("LANG", (222, r'kho', 'Khotanese'))
KW.add ("LANG", (223, r'kik', 'Kikuyu; Gikuyu'))
KW.add ("LANG", (224, r'kin', 'Kinyarwanda'))
KW.add ("LANG", (225, r'kir', 'Kirghiz; Kyrgyz'))
KW.add ("LANG", (226, r'kmb', 'Kimbundu'))
KW.add ("LANG", (227, r'kok', 'Konkani'))
KW.add ("LANG", (228, r'kom', 'Komi'))
KW.add ("LANG", (229, r'kon', 'Kongo'))
KW.add ("LANG", (230, r'kor', 'Korean'))
KW.add ("LANG", (231, r'kos', 'Kosraean'))
KW.add ("LANG", (232, r'kpe', 'Kpelle'))
KW.add ("LANG", (234, r'krl', 'Karelian'))
KW.add ("LANG", (236, r'kru', 'Kurukh'))
KW.add ("LANG", (241, r'lad', 'Ladino'))
KW.add ("LANG", (242, r'lah', 'Lahnda'))
KW.add ("LANG", (243, r'lam', 'Lamba'))
KW.add ("LANG", (244, r'lao', 'Lao'))
KW.add ("LANG", (245, r'lat', 'Latin'))
KW.add ("LANG", (246, r'lav', 'Latvian'))
KW.add ("LANG", (247, r'lez', 'Lezghian'))
KW.add ("LANG", (249, r'lin', 'Lingala'))
KW.add ("LANG", (251, r'lol', 'Mongo'))
KW.add ("LANG", (252, r'loz', 'Lozi'))
KW.add ("LANG", (253, r'ltz', 'Luxembourgish; Letzeburgesch'))
KW.add ("LANG", (255, r'lub', 'Luba-Katanga'))
KW.add ("LANG", (256, r'lug', 'Ganda'))
KW.add ("LANG", (257, r'lui', 'Luiseno'))
KW.add ("LANG", (258, r'lun', 'Lunda'))
KW.add ("LANG", (259, r'luo', 'Luo (Kenya and Tanzania)'))
KW.add ("LANG", (260, r'lus', 'Lushai'))
KW.add ("LANG", (262, r'mad', 'Madurese'))
KW.add ("LANG", (263, r'mag', 'Magahi'))
KW.add ("LANG", (264, r'mah', 'Marshallese'))
KW.add ("LANG", (266, r'mak', 'Makasar'))
KW.add ("LANG", (267, r'mal', 'Malayalam'))
KW.add ("LANG", (268, r'man', 'Mandingo'))
KW.add ("LANG", (269, r'mao', 'Maori'))
KW.add ("LANG", (270, r'map', 'Austronesian (Other)'))
KW.add ("LANG", (271, r'mar', 'Marathi'))
KW.add ("LANG", (272, r'mas', 'Masai'))
KW.add ("LANG", (273, r'may', 'Malay'))
KW.add ("LANG", (274, r'mdf', 'Moksha'))
KW.add ("LANG", (275, r'mdr', 'Mandar'))
KW.add ("LANG", (276, r'men', 'Mende'))
KW.add ("LANG", (277, r'mga', 'Irish, Middle (900-1200)'))
KW.add ("LANG", (278, r'mic', "Mi'kmaq; Micmac"))
KW.add ("LANG", (279, r'min', 'Minangkabau'))
KW.add ("LANG", (280, r'mis', 'Uncoded languages'))
KW.add ("LANG", (281, r'mkh', 'Mon-Khmer (Other)'))
KW.add ("LANG", (284, r'mnc', 'Manchu'))
KW.add ("LANG", (285, r'mni', 'Manipuri'))
KW.add ("LANG", (287, r'moh', 'Mohawk'))
KW.add ("LANG", (291, r'mul', 'Multiple languages'))
KW.add ("LANG", (292, r'mun', 'Munda languages'))
KW.add ("LANG", (294, r'mwl', 'Mirandese'))
KW.add ("LANG", (296, r'myn', 'Mayan languages'))
KW.add ("LANG", (298, r'nah', 'Nahuatl languages'))
KW.add ("LANG", (300, r'nap', 'Neapolitan'))
KW.add ("LANG", (305, r'ndo', 'Ndonga'))
KW.add ("LANG", (307, r'nep', 'Nepali'))
KW.add ("LANG", (308, r'new', 'Nepal Bhasa; Newari'))
KW.add ("LANG", (311, r'niu', 'Niuean'))
KW.add ("LANG", (283, r'mlt', 'Maltese'))
KW.add ("LANG", (314, r'nog', 'Nogai'))
KW.add ("LANG", (315, r'non', 'Norse, Old'))
KW.add ("LANG", (316, r'nor', 'Norwegian'))
KW.add ("LANG", (317, r'nqo', "N'Ko"))
KW.add ("LANG", (318, r'nso', 'Pedi; Sepedi; Northern Sotho'))
KW.add ("LANG", (319, r'nub', 'Nubian languages'))
KW.add ("LANG", (320, r'nwc', 'Classical Newari; Old Newari; Classical Nepal Bhasa'))
KW.add ("LANG", (321, r'nya', 'Chichewa; Chewa; Nyanja'))
KW.add ("LANG", (322, r'nym', 'Nyamwezi'))
KW.add ("LANG", (323, r'nyn', 'Nyankole'))
KW.add ("LANG", (324, r'nyo', 'Nyoro'))
KW.add ("LANG", (325, r'nzi', 'Nzima'))
KW.add ("LANG", (326, r'oci', 'Occitan (post 1500); Proven\xc3\xa7al'))
KW.add ("LANG", (327, r'oji', 'Ojibwa'))
KW.add ("LANG", (328, r'ori', 'Oriya'))
KW.add ("LANG", (329, r'orm', 'Oromo'))
KW.add ("LANG", (330, r'osa', 'Osage'))
KW.add ("LANG", (55, r'bin', 'Bini; Edo'))
KW.add ("LANG", (332, r'ota', 'Turkish, Ottoman (1500-1928)'))
KW.add ("LANG", (333, r'oto', 'Otomian languages'))
KW.add ("LANG", (334, r'paa', 'Papuan (Other)'))
KW.add ("LANG", (335, r'pag', 'Pangasinan'))
KW.add ("LANG", (337, r'pam', 'Pampanga; Kapampangan'))
KW.add ("LANG", (338, r'pan', 'Panjabi; Punjabi'))
KW.add ("LANG", (339, r'pap', 'Papiamento'))
KW.add ("LANG", (340, r'pau', 'Palauan'))
KW.add ("LANG", (341, r'peo', 'Persian, Old (ca.600-400 B.C.)'))
KW.add ("LANG", (342, r'per', 'Persian'))
KW.add ("LANG", (343, r'phi', 'Philippine (Other)'))
KW.add ("LANG", (344, r'phn', 'Phoenician'))
KW.add ("LANG", (345, r'pli', 'Pali'))
KW.add ("LANG", (346, r'pol', 'Polish'))
KW.add ("LANG", (347, r'pon', 'Pohnpeian'))
KW.add ("LANG", (349, r'pra', 'Prakrit languages'))
KW.add ("LANG", (350, r'pro', 'Proven\xc3\xa7al, Old (to 1500)'))
KW.add ("LANG", (351, r'pus', 'Pushto; Pashto'))
KW.add ("LANG", (353, r'que', 'Quechua'))
KW.add ("LANG", (354, r'raj', 'Rajasthani'))
KW.add ("LANG", (355, r'rap', 'Rapanui'))
KW.add ("LANG", (356, r'rar', 'Rarotongan; Cook Islands Maori'))
KW.add ("LANG", (358, r'roh', 'Romansh'))
KW.add ("LANG", (360, r'rum', 'Romanian'))
KW.add ("LANG", (362, r'rup', 'Aromanian; Arumanian; Macedo-Romanian'))
KW.add ("LANG", (363, r'rus', 'Russian'))
KW.add ("LANG", (364, r'sad', 'Sandawe'))
KW.add ("LANG", (365, r'sag', 'Sango'))
KW.add ("LANG", (368, r'sal', 'Salishan languages'))
KW.add ("LANG", (369, r'sam', 'Samaritan Aramaic'))
KW.add ("LANG", (371, r'sas', 'Sasak'))
KW.add ("LANG", (373, r'scc', 'Serbian'))
KW.add ("LANG", (375, r'sco', 'Scots'))
KW.add ("LANG", (376, r'scr', 'Croatian'))
KW.add ("LANG", (377, r'sel', 'Selkup'))
KW.add ("LANG", (378, r'sem', 'Semitic (Other)'))
KW.add ("LANG", (380, r'sgn', 'Sign Languages'))
KW.add ("LANG", (381, r'shn', 'Shan'))
KW.add ("LANG", (382, r'sid', 'Sidamo'))
KW.add ("LANG", (384, r'sio', 'Siouan languages'))
KW.add ("LANG", (385, r'sit', 'Sino-Tibetan (Other)'))
KW.add ("LANG", (386, r'sla', 'Slavic (Other)'))
KW.add ("LANG", (387, r'slo', 'Slovak'))
KW.add ("LANG", (388, r'slv', 'Slovenian'))
KW.add ("LANG", (389, r'sma', 'Southern Sami'))
KW.add ("LANG", (390, r'sme', 'Northern Sami'))
KW.add ("LANG", (391, r'smi', 'Sami languages (Other)'))
KW.add ("LANG", (392, r'smj', 'Lule Sami'))
KW.add ("LANG", (393, r'smn', 'Inari Sami'))
KW.add ("LANG", (394, r'smo', 'Samoan'))
KW.add ("LANG", (395, r'sms', 'Skolt Sami'))
KW.add ("LANG", (396, r'sna', 'Shona'))
KW.add ("LANG", (397, r'snd', 'Sindhi'))
KW.add ("LANG", (398, r'snk', 'Soninke'))
KW.add ("LANG", (399, r'sog', 'Sogdian'))
KW.add ("LANG", (400, r'som', 'Somali'))
KW.add ("LANG", (401, r'son', 'Songhai languages'))
KW.add ("LANG", (402, r'sot', 'Sotho, Southern'))
KW.add ("LANG", (67, r'byn', 'Blin; Bilin'))
KW.add ("LANG", (404, r'srd', 'Sardinian'))
KW.add ("LANG", (405, r'srn', 'Sranan Tongo'))
KW.add ("LANG", (406, r'srr', 'Serer'))
KW.add ("LANG", (407, r'ssa', 'Nilo-Saharan (Other)'))
KW.add ("LANG", (408, r'ssw', 'Swati'))
KW.add ("LANG", (410, r'sun', 'Sundanese'))
KW.add ("LANG", (411, r'sus', 'Susu'))
KW.add ("LANG", (412, r'sux', 'Sumerian'))
KW.add ("LANG", (413, r'swa', 'Swahili'))
KW.add ("LANG", (414, r'swe', 'Swedish'))
KW.add ("LANG", (416, r'syr', 'Syriac'))
KW.add ("LANG", (417, r'tah', 'Tahitian'))
KW.add ("LANG", (418, r'tai', 'Tai (Other)'))
KW.add ("LANG", (419, r'tam', 'Tamil'))
KW.add ("LANG", (421, r'tel', 'Telugu'))
KW.add ("LANG", (422, r'tem', 'Timne'))
KW.add ("LANG", (424, r'tet', 'Tetum'))
KW.add ("LANG", (426, r'tgl', 'Tagalog'))
KW.add ("LANG", (428, r'tib', 'Tibetan'))
KW.add ("LANG", (430, r'tir', 'Tigrinya'))
KW.add ("LANG", (432, r'tkl', 'Tokelau'))
KW.add ("LANG", (433, r'tlh', 'Klingon; tlhIngan-Hol'))
KW.add ("LANG", (434, r'tli', 'Tlingit'))
KW.add ("LANG", (435, r'tmh', 'Tamashek'))
KW.add ("LANG", (438, r'tpi', 'Tok Pisin'))
KW.add ("LANG", (73, r'ceb', 'Cebuano'))
KW.add ("LANG", (440, r'tsn', 'Tswana'))
KW.add ("LANG", (441, r'tso', 'Tsonga'))
KW.add ("LANG", (442, r'tuk', 'Turkmen'))
KW.add ("LANG", (447, r'tvl', 'Tuvalu'))
KW.add ("LANG", (448, r'twi', 'Twi'))
KW.add ("LANG", (454, r'umb', 'Umbundu'))
KW.add ("LANG", (457, r'uzb', 'Uzbek'))
KW.add ("LANG", (458, r'vai', 'Vai'))
KW.add ("LANG", (459, r'ven', 'Venda'))
KW.add ("LANG", (460, r'vie', 'Vietnamese'))
KW.add ("LANG", (462, r'vot', 'Votic'))
KW.add ("LANG", (463, r'wak', 'Wakashan languages'))
KW.add ("LANG", (464, r'wal', 'Walamo'))
KW.add ("LANG", (465, r'war', 'Waray'))
KW.add ("LANG", (467, r'wel', 'Welsh'))
KW.add ("LANG", (468, r'wen', 'Sorbian languages'))
KW.add ("LANG", (471, r'xal', 'Kalmyk; Oirat'))
KW.add ("LANG", (475, r'yid', 'Yiddish'))
KW.add ("LANG", (476, r'yor', 'Yoruba'))
KW.add ("LANG", (480, r'zen', 'Zenaga'))
KW.add ("LANG", (481, r'zha', 'Zhuang; Chuang'))
KW.add ("LANG", (483, r'zul', 'Zulu'))
KW.add ("LANG", (484, r'zun', 'Zuni'))
KW.add ("LANG", (485, r'zxx', 'No linguistic content'))
KW.add ("LANG", (486, r'zza', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'))
KW.add ("LANG", (357, r'roa', 'Romance (Other)'))
KW.add ("LANG", (425, r'tgk', 'Tajik'))
KW.add ("LANG", (427, r'tha', 'Thai'))
KW.add ("LANG", (431, r'tiv', 'Tiv'))
KW.add ("LANG", (359, r'rom', 'Romany'))
KW.add ("LANG", (436, r'tog', 'Tonga (Nyasa)'))
KW.add ("LANG", (437, r'ton', 'Tonga (Tonga Islands)'))
KW.add ("LANG", (429, r'tig', 'Tigre'))
KW.add ("LANG", (361, r'run', 'Rundi'))
KW.add ("LANG", (443, r'tum', 'Tumbuka'))
KW.add ("LANG", (444, r'tup', 'Tupi languages'))
KW.add ("LANG", (108, r'dgr', 'Dogrib'))
KW.add ("LANG", (452, r'uig', 'Uighur; Uyghur'))
KW.add ("LANG", (453, r'ukr', 'Ukrainian'))
KW.add ("LANG", (295, r'mwr', 'Marwari'))
KW.add ("LANG", (455, r'und', 'Undetermined'))
KW.add ("LANG", (461, r'vol', 'Volap\xc3\xbck'))
KW.add ("LANG", (466, r'was', 'Washo'))
KW.add ("LANG", (366, r'sah', 'Yakut'))
KW.add ("LANG", (470, r'wol', 'Wolof'))
KW.add ("LANG", (409, r'suk', 'Sukuma'))
KW.add ("LANG", (26, r'arp', 'Arapaho'))
KW.add ("LANG", (367, r'sai', 'South American Indian (Other)'))
KW.add ("LANG", (473, r'yao', 'Yao'))
KW.add ("LANG", (477, r'ypk', 'Yupik languages'))
KW.add ("LANG", (478, r'zap', 'Zapotec'))
KW.add ("LANG", (482, r'znd', 'Zande languages'))
KW.add ("LANG", (370, r'san', 'Sanskrit'))
KW.add ("LANG", (302, r'nav', 'Navajo; Navaho'))
KW.add ("LANG", (374, r'scn', 'Sicilian'))
KW.add ("LANG", (171, r'hau', 'Hausa'))
KW.add ("LANG", (239, r'kur', 'Kurdish'))
KW.add ("LANG", (348, r'por', 'Portuguese'))
KW.add ("LANG", (312, r'nno', 'Norwegian Nynorsk; Nynorsk, Norwegian'))
KW.add ("LANG", (450, r'udm', 'Udmurt'))
KW.add ("LANG", (451, r'uga', 'Ugaritic'))
KW.add ("LANG", (383, r'sin', 'Sinhala; Sinhalese'))
KW.add ("LANG", (372, r'sat', 'Santali'))
KW.add ("LANG", (479, r'zbl', 'Blissymbols; Blissymbolics; Bliss'))
KW.add ("LANG", (233, r'krc', 'Karachay-Balkar'))
KW.add ("LANG", (235, r'kro', 'Kru languages'))
KW.add ("LANG", (456, r'urd', 'Urdu'))
KW.add ("LANG", (237, r'kua', 'Kuanyama; Kwanyama'))
KW.add ("LANG", (238, r'kum', 'Kumyk'))
KW.add ("LANG", (240, r'kut', 'Kutenai'))
KW.add ("LANG", (423, r'ter', 'Tereno'))
KW.add ("LANG", (446, r'tut', 'Altaic (Other)'))
KW.add ("LANG", (248, r'lim', 'Limburgan; Limburger; Limburgish'))
KW.add ("LANG", (250, r'lit', 'Lithuanian'))
KW.add ("LANG", (50, r'ben', 'Bengali'))
KW.add ("LANG", (254, r'lua', 'Luba-Lulua'))
KW.add ("LANG", (261, r'mac', 'Macedonian'))
KW.add ("LANG", (122, r'elx', 'Elamite'))
KW.add ("LANG", (379, r'sga', 'Irish, Old (to 900)'))
KW.add ("LANG", (420, r'tat', 'Tatar'))
KW.add ("LANG", (282, r'mlg', 'Malagasy'))
KW.add ("LANG", (286, r'mno', 'Manobo languages'))
KW.add ("LANG", (288, r'mol', 'Moldavian'))
KW.add ("LANG", (289, r'mon', 'Mongolian'))
KW.add ("LANG", (290, r'mos', 'Mossi'))
KW.add ("LANG", (293, r'mus', 'Creek'))
KW.add ("LANG", (297, r'myv', 'Erzya'))
KW.add ("LANG", (299, r'nai', 'North American Indian'))
KW.add ("LANG", (469, r'wln', 'Walloon'))
KW.add ("LANG", (301, r'nau', 'Nauru'))
KW.add ("LANG", (303, r'nbl', 'Ndebele, South; South Ndebele'))
KW.add ("LANG", (265, r'mai', 'Maithili'))
KW.add ("LANG", (304, r'nde', 'Ndebele, North; North Ndebele'))
KW.add ("LANG", (306, r'nds', 'Low German; Low Saxon; German, Low; Saxon, Low'))
KW.add ("LANG", (309, r'nia', 'Nias'))
KW.add ("LANG", (310, r'nic', 'Niger-Kordofanian (Other)'))
KW.add ("LANG", (403, r'spa', 'Spanish; Castilian'))
KW.add ("LANG", (313, r'nob', 'Bokm\xc3\xa5l, Norwegian; Norwegian Bokm\xc3\xa5l'))
KW.add ("LANG", (472, r'xho', 'Xhosa'))
KW.add ("LANG", (449, r'tyv', 'Tuvinian'))
KW.add ("LANG", (474, r'yap', 'Yapese'))
KW.add ("LANG", (439, r'tsi', 'Tsimshian'))
KW.add ("LANG", (331, r'oss', 'Ossetian; Ossetic'))
KW.add ("LANG", (336, r'pal', 'Pahlavi'))
KW.add ("LANG", (415, r'syc', 'Classical Syriac'))
KW.add ("LANG", (445, r'tur', 'Turkish'))
KW.add ("MISC", (1, r'X', 'rude or X-rated term (not displayed in educational software)'))
KW.add ("MISC", (2, r'abbr', 'abbreviation'))
KW.add ("MISC", (3, r'arch', 'archaism'))
KW.add ("MISC", (4, r'chn', "children's language"))
KW.add ("MISC", (5, r'col', 'colloquialism'))
KW.add ("MISC", (6, r'derog', 'derogatory'))
KW.add ("MISC", (7, r'eK', 'exclusively kanji'))
KW.add ("MISC", (8, r'fam', 'familiar language'))
KW.add ("MISC", (9, r'fem', 'female term or language'))
KW.add ("MISC", (11, r'hon', 'honorific or respectful (sonkeigo) language'))
KW.add ("MISC", (12, r'hum', 'humble (kenjougo) language'))
KW.add ("MISC", (13, r'id', 'idiomatic expression'))
KW.add ("MISC", (14, r'm-sl', 'manga slang'))
KW.add ("MISC", (17, r'obs', 'obsolete term'))
KW.add ("MISC", (18, r'obsc', 'obscure term'))
KW.add ("MISC", (19, r'pol', 'polite (teineigo) language'))
KW.add ("MISC", (20, r'rare', 'rare'))
KW.add ("MISC", (21, r'sl', 'slang'))
KW.add ("MISC", (22, r'uk', 'word usually written using kana alone'))
KW.add ("MISC", (24, r'vulg', 'vulgar expression or word'))
KW.add ("MISC", (25, r'sens', 'sensitive'))
KW.add ("MISC", (26, r'poet', 'poetical term'))
KW.add ("MISC", (27, r'on-mim', 'onomatopoeic or mimetic word'))
KW.add ("MISC", (81, r'proverb', 'proverb'))
KW.add ("MISC", (82, r'aphorism', 'aphorism (pithy saying)'))
KW.add ("MISC", (83, r'quote', 'quotation'))
KW.add ("MISC", (15, r'male', 'male term or language'))
KW.add ("POS", (1, r'adj-i', 'adjective (keiyoushi)'))
KW.add ("POS", (2, r'adj-na', 'adjectival nouns or quasi-adjectives (keiyodoshi)'))
KW.add ("POS", (3, r'adj-no', "nouns which may take the genitive case particle `no'"))
KW.add ("POS", (4, r'adj-pn', 'pre-noun adjectival (rentaishi)'))
KW.add ("POS", (5, r'adj-t', "`taru' adjective"))
KW.add ("POS", (6, r'adv', 'adverb (fukushi)'))
KW.add ("POS", (8, r'adv-to', "adverb taking the `to' particle"))
KW.add ("POS", (9, r'aux', 'auxiliary'))
KW.add ("POS", (10, r'aux-adj', 'auxiliary adjective'))
KW.add ("POS", (11, r'aux-v', 'auxiliary verb'))
KW.add ("POS", (12, r'conj', 'conjunction'))
KW.add ("POS", (13, r'exp', 'Expressions (phrases, clauses, etc.)'))
KW.add ("POS", (14, r'int', 'interjection (kandoushi)'))
KW.add ("POS", (17, r'n', 'noun (common) (futsuumeishi)'))
KW.add ("POS", (18, r'n-adv', 'adverbial noun (fukushitekimeishi)'))
KW.add ("POS", (19, r'n-suf', 'noun, used as a suffix'))
KW.add ("POS", (20, r'n-pref', 'noun, used as a prefix'))
KW.add ("POS", (21, r'n-t', 'noun (temporal) (jisoumeishi)'))
KW.add ("POS", (24, r'num', 'numeric'))
KW.add ("POS", (25, r'pref', 'prefix'))
KW.add ("POS", (26, r'prt', 'particle'))
KW.add ("POS", (27, r'suf', 'suffix'))
KW.add ("POS", (28, r'v1', 'Ichidan verb'))
KW.add ("POS", (29, r'v5', 'Godan verb (not completely classified)'))
KW.add ("POS", (30, r'v5aru', 'Godan verb - -aru special class'))
KW.add ("POS", (31, r'v5b', "Godan verb with `bu' ending"))
KW.add ("POS", (33, r'v5k', "Godan verb with `ku' ending"))
KW.add ("POS", (34, r'v5k-s', 'Godan verb - Iku/Yuku special class'))
KW.add ("POS", (35, r'v5m', "Godan verb with `mu' ending"))
KW.add ("POS", (36, r'v5n', "Godan verb with `nu' ending"))
KW.add ("POS", (37, r'v5r', "Godan verb with `ru' ending"))
KW.add ("POS", (38, r'v5r-i', "Godan verb with `ru' ending (irregular verb)"))
KW.add ("POS", (39, r'v5s', "Godan verb with `su' ending"))
KW.add ("POS", (40, r'v5t', "Godan verb with `tsu' ending"))
KW.add ("POS", (41, r'v5u', "Godan verb with `u' ending"))
KW.add ("POS", (42, r'v5u-s', "Godan verb with `u' ending (special class)"))
KW.add ("POS", (43, r'v5uru', 'Godan verb - Uru old class verb (old form of Eru)'))
KW.add ("POS", (44, r'vi', 'intransitive verb'))
KW.add ("POS", (45, r'vk', 'Kuru verb - special class'))
KW.add ("POS", (46, r'vs', 'noun or participle which takes the aux. verb suru'))
KW.add ("POS", (47, r'vs-s', 'suru verb - special class'))
KW.add ("POS", (48, r'vs-i', 'suru verb - irregular'))
KW.add ("POS", (49, r'vz', 'Ichidan verb - zuru verb (alternative form of -jiru verbs)'))
KW.add ("POS", (50, r'vt', 'transitive verb'))
KW.add ("POS", (51, r'ctr', 'counter'))
KW.add ("POS", (52, r'vn', 'irregular nu verb'))
KW.add ("POS", (53, r'v4r', "Yondan verb with `ru' ending (archaic)"))
KW.add ("POS", (55, r'v5z', "Godan verb with `zu' ending"))
KW.add ("POS", (56, r'adj-f', 'noun or verb acting prenominally'))
KW.add ("POS", (185, r'product', 'product name'))
KW.add ("POS", (181, r'surname', 'family or surname'))
KW.add ("POS", (182, r'place', 'place name'))
KW.add ("POS", (183, r'unclass', 'unclassified name'))
KW.add ("POS", (184, r'company', 'company name'))
KW.add ("POS", (186, r'masc', 'male given name or forename'))
KW.add ("POS", (187, r'fem', 'female given name or forename'))
KW.add ("POS", (188, r'person', 'full name of a particular person'))
KW.add ("POS", (189, r'given', 'given name or forename, gender not specified'))
KW.add ("POS", (190, r'station', 'railway station'))
KW.add ("POS", (32, r'v5g', "Godan verb with `gu' ending"))
KW.add ("POS", (57, r'adj', 'former adjective classification (being removed)'))
KW.add ("RINF", (128, r'on', 'on-yomi'))
KW.add ("RINF", (1, r'gikun', 'gikun (meaning) reading'))
KW.add ("RINF", (2, r'ok', 'out-dated or obsolete kana usage'))
KW.add ("RINF", (3, r'ik', 'word containing irregular kana usage'))
KW.add ("RINF", (4, r'uK', 'word usually written using kanji alone'))
KW.add ("RINF", (129, r'kan', 'on-yomi, kan'))
KW.add ("RINF", (131, r'tou', 'on-yomi, tou'))
KW.add ("RINF", (21, r'oik', 'old or irregular kana form'))
KW.add ("RINF", (132, r'kanyou', "on-yomi, kan\\'you"))
KW.add ("RINF", (130, r'go', 'on-yomi, go'))
KW.add ("RINF", (103, r'name', 'reading used only in names (nanori)'))
KW.add ("RINF", (104, r'rad', 'reading used as name of radical'))
KW.add ("RINF", (105, r'jouyou', 'approved reading for jouyou kanji'))
KW.add ("RINF", (106, r'kun', 'kun-yomi'))
KW.add ("STAT", (1, r'N', 'New'))
KW.add ("STAT", (2, r'A', 'Active'))
KW.add ("STAT", (4, r'D', 'Deleted'))
KW.add ("STAT", (6, r'R', 'Rejected'))
KW.add ("XREF", (1, r'syn', 'Synonym'))
KW.add ("XREF", (2, r'ant', 'Antonym'))
KW.add ("XREF", (3, r'see', 'See also'))
KW.add ("XREF", (4, r'cf', 'C.f.'))
KW.add ("XREF", (5, r'ex', 'Usage example'))
KW.add ("XREF", (6, r'uses', 'Uses'))
KW.add ("XREF", (7, r'pref', 'Preferred'))
KW.add ("XREF", (8, r'kvar', 'Kanji variant'))

KWCINF_nelson_c = 1
KWCINF_nelson_n = 2
KWCINF_halpern_njecd = 3
KWCINF_halpern_kkld = 4
KWCINF_heisig = 5
KWCINF_gakken = 6
KWCINF_oneill_names = 7
KWCINF_oneill_kk = 8
KWCINF_moro = 9
KWCINF_henshall = 10
KWCINF_sh_kk = 11
KWCINF_sakade = 12
KWCINF_tutt_cards = 13
KWCINF_crowley = 14
KWCINF_kanji_in_ctx = 15
KWCINF_busy_people = 16
KWCINF_kodansha_comp = 17
KWCINF_skip = 18
KWCINF_deroo = 21
KWCINF_misclass = 22
KWCINF_pinyin = 23
KWCINF_strokes = 24
KWCINF_jis208 = 25
KWCINF_jis212 = 26
KWCINF_jis213 = 27
KWCINF_henshall3 = 28
KWCINF_korean_h = 29
KWCINF_korean_r = 30
KWCINF_jf_cards = 31
KWCINF_nelson_rad = 32
KWCINF_skip_mis = 33
KWCINF_s_h = 34
KWCINF_sh_desc = 19
KWCINF_four_corner = 20
KWDIAL_std = 1
KWDIAL_ksb = 2
KWDIAL_ktb = 3
KWDIAL_kyb = 4
KWDIAL_osb = 5
KWDIAL_tsb = 6
KWDIAL_thb = 7
KWDIAL_tsug = 8
KWDIAL_rkb = 10
KWDIAL_kyu = 9
KWFLD_Buddh = 1
KWFLD_comp = 2
KWFLD_food = 3
KWFLD_geom = 4
KWFLD_ling = 5
KWFLD_MA = 6
KWFLD_math = 7
KWFLD_mil = 8
KWFLD_physics = 9
KWFREQ_ichi = 1
KWFREQ_gai = 2
KWFREQ_spec = 4
KWFREQ_nf = 5
KWFREQ_gA = 6
KWFREQ_news = 7
KWGINF_equ = 1
KWGINF_lit = 2
KWGINF_id = 3
KWGINF_expl = 4
KWKINF_iK = 1
KWKINF_io = 2
KWKINF_oK = 3
KWKINF_ateji = 5
KWKINF_ik = 4
KWLANG_eng = 1
KWLANG_abk = 2
KWLANG_ace = 3
KWLANG_ach = 4
KWLANG_ada = 5
KWLANG_ady = 6
KWLANG_afa = 7
KWLANG_afh = 8
KWLANG_afr = 9
KWLANG_ain = 10
KWLANG_aka = 11
KWLANG_akk = 12
KWLANG_alb = 13
KWLANG_ale = 14
KWLANG_alg = 15
KWLANG_alt = 16
KWLANG_amh = 17
KWLANG_ang = 18
KWLANG_anp = 19
KWLANG_apa = 20
KWLANG_ara = 21
KWLANG_arc = 22
KWLANG_arg = 23
KWLANG_arm = 24
KWLANG_arn = 25
KWLANG_art = 27
KWLANG_arw = 28
KWLANG_asm = 29
KWLANG_ast = 30
KWLANG_ath = 31
KWLANG_aus = 32
KWLANG_ava = 33
KWLANG_ave = 34
KWLANG_awa = 35
KWLANG_aym = 36
KWLANG_aze = 37
KWLANG_bad = 38
KWLANG_bai = 39
KWLANG_bak = 40
KWLANG_bal = 41
KWLANG_bam = 42
KWLANG_ban = 43
KWLANG_baq = 44
KWLANG_bas = 45
KWLANG_bat = 46
KWLANG_bej = 47
KWLANG_bel = 48
KWLANG_bem = 49
KWLANG_ber = 51
KWLANG_bho = 52
KWLANG_bih = 53
KWLANG_bik = 54
KWLANG_bis = 56
KWLANG_bla = 57
KWLANG_bnt = 58
KWLANG_bos = 59
KWLANG_bra = 60
KWLANG_bre = 61
KWLANG_btk = 62
KWLANG_bua = 63
KWLANG_bug = 64
KWLANG_bul = 65
KWLANG_bur = 66
KWLANG_cad = 68
KWLANG_cai = 69
KWLANG_car = 70
KWLANG_cat = 71
KWLANG_cau = 72
KWLANG_cel = 74
KWLANG_cha = 75
KWLANG_chb = 76
KWLANG_che = 77
KWLANG_chg = 78
KWLANG_chi = 79
KWLANG_chk = 80
KWLANG_chm = 81
KWLANG_chn = 82
KWLANG_cho = 83
KWLANG_chp = 84
KWLANG_chr = 85
KWLANG_chu = 86
KWLANG_chv = 87
KWLANG_chy = 88
KWLANG_cmc = 89
KWLANG_cop = 90
KWLANG_cor = 91
KWLANG_cos = 92
KWLANG_cpe = 93
KWLANG_cpf = 94
KWLANG_cpp = 95
KWLANG_cre = 96
KWLANG_crh = 97
KWLANG_crp = 98
KWLANG_csb = 99
KWLANG_cus = 100
KWLANG_cze = 101
KWLANG_dak = 102
KWLANG_dan = 103
KWLANG_dar = 104
KWLANG_day = 105
KWLANG_del = 106
KWLANG_den = 107
KWLANG_din = 109
KWLANG_div = 110
KWLANG_doi = 111
KWLANG_dra = 112
KWLANG_dsb = 113
KWLANG_dua = 114
KWLANG_dum = 115
KWLANG_dut = 116
KWLANG_dyu = 117
KWLANG_dzo = 118
KWLANG_efi = 119
KWLANG_egy = 120
KWLANG_eka = 121
KWLANG_enm = 124
KWLANG_epo = 125
KWLANG_est = 126
KWLANG_ewe = 127
KWLANG_ewo = 128
KWLANG_fan = 129
KWLANG_fao = 130
KWLANG_fat = 131
KWLANG_fij = 132
KWLANG_fil = 133
KWLANG_fin = 134
KWLANG_fiu = 135
KWLANG_fon = 136
KWLANG_fre = 137
KWLANG_frm = 138
KWLANG_fro = 139
KWLANG_frr = 140
KWLANG_frs = 141
KWLANG_fry = 142
KWLANG_ful = 143
KWLANG_fur = 144
KWLANG_gaa = 145
KWLANG_gay = 146
KWLANG_gba = 147
KWLANG_gem = 148
KWLANG_geo = 149
KWLANG_ger = 150
KWLANG_gez = 151
KWLANG_gil = 152
KWLANG_gla = 153
KWLANG_gle = 154
KWLANG_glg = 155
KWLANG_glv = 156
KWLANG_gmh = 157
KWLANG_goh = 158
KWLANG_gon = 159
KWLANG_gor = 160
KWLANG_got = 161
KWLANG_grb = 162
KWLANG_grc = 163
KWLANG_gre = 164
KWLANG_grn = 165
KWLANG_gsw = 166
KWLANG_guj = 167
KWLANG_gwi = 168
KWLANG_hai = 169
KWLANG_hat = 170
KWLANG_haw = 172
KWLANG_heb = 173
KWLANG_her = 174
KWLANG_hil = 175
KWLANG_him = 176
KWLANG_hin = 177
KWLANG_hit = 178
KWLANG_hmn = 179
KWLANG_hmo = 180
KWLANG_hsb = 181
KWLANG_hun = 182
KWLANG_hup = 183
KWLANG_iba = 184
KWLANG_ibo = 185
KWLANG_ice = 186
KWLANG_ido = 187
KWLANG_iii = 188
KWLANG_ijo = 189
KWLANG_iku = 190
KWLANG_ile = 191
KWLANG_ilo = 192
KWLANG_ina = 193
KWLANG_inc = 194
KWLANG_ind = 195
KWLANG_ine = 196
KWLANG_inh = 197
KWLANG_ipk = 198
KWLANG_ira = 199
KWLANG_iro = 200
KWLANG_ita = 201
KWLANG_jav = 202
KWLANG_jbo = 203
KWLANG_jpn = 204
KWLANG_jpr = 205
KWLANG_jrb = 206
KWLANG_kaa = 207
KWLANG_kab = 208
KWLANG_kac = 209
KWLANG_kal = 210
KWLANG_kam = 211
KWLANG_kan = 212
KWLANG_kar = 213
KWLANG_kas = 214
KWLANG_kau = 215
KWLANG_kaw = 216
KWLANG_kaz = 217
KWLANG_kbd = 218
KWLANG_kha = 219
KWLANG_khi = 220
KWLANG_khm = 221
KWLANG_kho = 222
KWLANG_kik = 223
KWLANG_kin = 224
KWLANG_kir = 225
KWLANG_kmb = 226
KWLANG_kok = 227
KWLANG_kom = 228
KWLANG_kon = 229
KWLANG_kor = 230
KWLANG_kos = 231
KWLANG_kpe = 232
KWLANG_krl = 234
KWLANG_kru = 236
KWLANG_lad = 241
KWLANG_lah = 242
KWLANG_lam = 243
KWLANG_lao = 244
KWLANG_lat = 245
KWLANG_lav = 246
KWLANG_lez = 247
KWLANG_lin = 249
KWLANG_lol = 251
KWLANG_loz = 252
KWLANG_ltz = 253
KWLANG_lub = 255
KWLANG_lug = 256
KWLANG_lui = 257
KWLANG_lun = 258
KWLANG_luo = 259
KWLANG_lus = 260
KWLANG_mad = 262
KWLANG_mag = 263
KWLANG_mah = 264
KWLANG_mak = 266
KWLANG_mal = 267
KWLANG_man = 268
KWLANG_mao = 269
KWLANG_map = 270
KWLANG_mar = 271
KWLANG_mas = 272
KWLANG_may = 273
KWLANG_mdf = 274
KWLANG_mdr = 275
KWLANG_men = 276
KWLANG_mga = 277
KWLANG_mic = 278
KWLANG_min = 279
KWLANG_mis = 280
KWLANG_mkh = 281
KWLANG_mnc = 284
KWLANG_mni = 285
KWLANG_moh = 287
KWLANG_mul = 291
KWLANG_mun = 292
KWLANG_mwl = 294
KWLANG_myn = 296
KWLANG_nah = 298
KWLANG_nap = 300
KWLANG_ndo = 305
KWLANG_nep = 307
KWLANG_new = 308
KWLANG_niu = 311
KWLANG_mlt = 283
KWLANG_nog = 314
KWLANG_non = 315
KWLANG_nor = 316
KWLANG_nqo = 317
KWLANG_nso = 318
KWLANG_nub = 319
KWLANG_nwc = 320
KWLANG_nya = 321
KWLANG_nym = 322
KWLANG_nyn = 323
KWLANG_nyo = 324
KWLANG_nzi = 325
KWLANG_oci = 326
KWLANG_oji = 327
KWLANG_ori = 328
KWLANG_orm = 329
KWLANG_osa = 330
KWLANG_bin = 55
KWLANG_ota = 332
KWLANG_oto = 333
KWLANG_paa = 334
KWLANG_pag = 335
KWLANG_pam = 337
KWLANG_pan = 338
KWLANG_pap = 339
KWLANG_pau = 340
KWLANG_peo = 341
KWLANG_per = 342
KWLANG_phi = 343
KWLANG_phn = 344
KWLANG_pli = 345
KWLANG_pol = 346
KWLANG_pon = 347
KWLANG_pra = 349
KWLANG_pro = 350
KWLANG_pus = 351
KWLANG_que = 353
KWLANG_raj = 354
KWLANG_rap = 355
KWLANG_rar = 356
KWLANG_roh = 358
KWLANG_rum = 360
KWLANG_rup = 362
KWLANG_rus = 363
KWLANG_sad = 364
KWLANG_sag = 365
KWLANG_sal = 368
KWLANG_sam = 369
KWLANG_sas = 371
KWLANG_scc = 373
KWLANG_sco = 375
KWLANG_scr = 376
KWLANG_sel = 377
KWLANG_sem = 378
KWLANG_sgn = 380
KWLANG_shn = 381
KWLANG_sid = 382
KWLANG_sio = 384
KWLANG_sit = 385
KWLANG_sla = 386
KWLANG_slo = 387
KWLANG_slv = 388
KWLANG_sma = 389
KWLANG_sme = 390
KWLANG_smi = 391
KWLANG_smj = 392
KWLANG_smn = 393
KWLANG_smo = 394
KWLANG_sms = 395
KWLANG_sna = 396
KWLANG_snd = 397
KWLANG_snk = 398
KWLANG_sog = 399
KWLANG_som = 400
KWLANG_son = 401
KWLANG_sot = 402
KWLANG_byn = 67
KWLANG_srd = 404
KWLANG_srn = 405
KWLANG_srr = 406
KWLANG_ssa = 407
KWLANG_ssw = 408
KWLANG_sun = 410
KWLANG_sus = 411
KWLANG_sux = 412
KWLANG_swa = 413
KWLANG_swe = 414
KWLANG_syr = 416
KWLANG_tah = 417
KWLANG_tai = 418
KWLANG_tam = 419
KWLANG_tel = 421
KWLANG_tem = 422
KWLANG_tet = 424
KWLANG_tgl = 426
KWLANG_tib = 428
KWLANG_tir = 430
KWLANG_tkl = 432
KWLANG_tlh = 433
KWLANG_tli = 434
KWLANG_tmh = 435
KWLANG_tpi = 438
KWLANG_ceb = 73
KWLANG_tsn = 440
KWLANG_tso = 441
KWLANG_tuk = 442
KWLANG_tvl = 447
KWLANG_twi = 448
KWLANG_umb = 454
KWLANG_uzb = 457
KWLANG_vai = 458
KWLANG_ven = 459
KWLANG_vie = 460
KWLANG_vot = 462
KWLANG_wak = 463
KWLANG_wal = 464
KWLANG_war = 465
KWLANG_wel = 467
KWLANG_wen = 468
KWLANG_xal = 471
KWLANG_yid = 475
KWLANG_yor = 476
KWLANG_zen = 480
KWLANG_zha = 481
KWLANG_zul = 483
KWLANG_zun = 484
KWLANG_zxx = 485
KWLANG_zza = 486
KWLANG_roa = 357
KWLANG_tgk = 425
KWLANG_tha = 427
KWLANG_tiv = 431
KWLANG_rom = 359
KWLANG_tog = 436
KWLANG_ton = 437
KWLANG_tig = 429
KWLANG_run = 361
KWLANG_tum = 443
KWLANG_tup = 444
KWLANG_dgr = 108
KWLANG_uig = 452
KWLANG_ukr = 453
KWLANG_mwr = 295
KWLANG_und = 455
KWLANG_vol = 461
KWLANG_was = 466
KWLANG_sah = 366
KWLANG_wol = 470
KWLANG_suk = 409
KWLANG_arp = 26
KWLANG_sai = 367
KWLANG_yao = 473
KWLANG_ypk = 477
KWLANG_zap = 478
KWLANG_znd = 482
KWLANG_san = 370
KWLANG_nav = 302
KWLANG_scn = 374
KWLANG_hau = 171
KWLANG_kur = 239
KWLANG_por = 348
KWLANG_nno = 312
KWLANG_udm = 450
KWLANG_uga = 451
KWLANG_sin = 383
KWLANG_sat = 372
KWLANG_zbl = 479
KWLANG_krc = 233
KWLANG_kro = 235
KWLANG_urd = 456
KWLANG_kua = 237
KWLANG_kum = 238
KWLANG_kut = 240
KWLANG_ter = 423
KWLANG_tut = 446
KWLANG_lim = 248
KWLANG_lit = 250
KWLANG_ben = 50
KWLANG_lua = 254
KWLANG_mac = 261
KWLANG_elx = 122
KWLANG_sga = 379
KWLANG_tat = 420
KWLANG_mlg = 282
KWLANG_mno = 286
KWLANG_mol = 288
KWLANG_mon = 289
KWLANG_mos = 290
KWLANG_mus = 293
KWLANG_myv = 297
KWLANG_nai = 299
KWLANG_wln = 469
KWLANG_nau = 301
KWLANG_nbl = 303
KWLANG_mai = 265
KWLANG_nde = 304
KWLANG_nds = 306
KWLANG_nia = 309
KWLANG_nic = 310
KWLANG_spa = 403
KWLANG_nob = 313
KWLANG_xho = 472
KWLANG_tyv = 449
KWLANG_yap = 474
KWLANG_tsi = 439
KWLANG_oss = 331
KWLANG_pal = 336
KWLANG_syc = 415
KWLANG_tur = 445
KWMISC_X = 1
KWMISC_abbr = 2
KWMISC_arch = 3
KWMISC_chn = 4
KWMISC_col = 5
KWMISC_derog = 6
KWMISC_eK = 7
KWMISC_fam = 8
KWMISC_fem = 9
KWMISC_hon = 11
KWMISC_hum = 12
KWMISC_id = 13
KWMISC_m_sl = 14
KWMISC_obs = 17
KWMISC_obsc = 18
KWMISC_pol = 19
KWMISC_rare = 20
KWMISC_sl = 21
KWMISC_uk = 22
KWMISC_vulg = 24
KWMISC_sens = 25
KWMISC_poet = 26
KWMISC_on_mim = 27
KWMISC_proverb = 81
KWMISC_aphorism = 82
KWMISC_quote = 83
KWMISC_male = 15
KWPOS_adj_i = 1
KWPOS_adj_na = 2
KWPOS_adj_no = 3
KWPOS_adj_pn = 4
KWPOS_adj_t = 5
KWPOS_adv = 6
KWPOS_adv_to = 8
KWPOS_aux = 9
KWPOS_aux_adj = 10
KWPOS_aux_v = 11
KWPOS_conj = 12
KWPOS_exp = 13
KWPOS_int = 14
KWPOS_n = 17
KWPOS_n_adv = 18
KWPOS_n_suf = 19
KWPOS_n_pref = 20
KWPOS_n_t = 21
KWPOS_num = 24
KWPOS_pref = 25
KWPOS_prt = 26
KWPOS_suf = 27
KWPOS_v1 = 28
KWPOS_v5 = 29
KWPOS_v5aru = 30
KWPOS_v5b = 31
KWPOS_v5k = 33
KWPOS_v5k_s = 34
KWPOS_v5m = 35
KWPOS_v5n = 36
KWPOS_v5r = 37
KWPOS_v5r_i = 38
KWPOS_v5s = 39
KWPOS_v5t = 40
KWPOS_v5u = 41
KWPOS_v5u_s = 42
KWPOS_v5uru = 43
KWPOS_vi = 44
KWPOS_vk = 45
KWPOS_vs = 46
KWPOS_vs_s = 47
KWPOS_vs_i = 48
KWPOS_vz = 49
KWPOS_vt = 50
KWPOS_ctr = 51
KWPOS_vn = 52
KWPOS_v4r = 53
KWPOS_v5z = 55
KWPOS_adj_f = 56
KWPOS_product = 185
KWPOS_surname = 181
KWPOS_place = 182
KWPOS_unclass = 183
KWPOS_company = 184
KWPOS_masc = 186
KWPOS_fem = 187
KWPOS_person = 188
KWPOS_given = 189
KWPOS_station = 190
KWPOS_v5g = 32
KWPOS_adj = 57
KWRINF_on = 128
KWRINF_gikun = 1
KWRINF_ok = 2
KWRINF_ik = 3
KWRINF_uK = 4
KWRINF_kan = 129
KWRINF_tou = 131
KWRINF_oik = 21
KWRINF_kanyou = 132
KWRINF_go = 130
KWRINF_name = 103
KWRINF_rad = 104
KWRINF_jouyou = 105
KWRINF_kun = 106
KWSTAT_N = 1
KWSTAT_A = 2
KWSTAT_D = 4
KWSTAT_R = 6
KWXREF_syn = 1
KWXREF_ant = 2
KWXREF_see = 3
KWXREF_cf = 4
KWXREF_ex = 5
KWXREF_uses = 6
KWXREF_pref = 7
KWXREF_kvar = 8
