%_xmllang = (
	    'eng' => 1,	# English
	    'abk' => 2,	# Abkhazian
	    'ace' => 3,	# Achinese
	    'ach' => 4,	# Acoli
	    'ada' => 5,	# Adangme
	    'ady' => 6,	# Adyghe; Adygei
	    'afa' => 7,	# Afro-Asiatic (Other)
	    'afh' => 8,	# Afrihili
	    'afr' => 9,	# Afrikaans
	    'ain' => 10,	# Ainu
	    'aka' => 11,	# Akan
	    'akk' => 12,	# Akkadian
	    'alb' => 13,	# Albanian
	    'ale' => 14,	# Aleut
	    'alg' => 15,	# Algonquian languages
	    'alt' => 16,	# Southern Altai
	    'amh' => 17,	# Amharic
	    'ang' => 18,	# English, Old (ca.450-1100)
	    'anp' => 19,	# Angika
	    'apa' => 20,	# Apache languages
	    'ara' => 21,	# Arabic
	    'arc' => 22,	# Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)
	    'arg' => 23,	# Aragonese
	    'arm' => 24,	# Armenian
	    'arn' => 25,	# Mapudungun; Mapuche
	    'arp' => 26,	# Arapaho
	    'art' => 27,	# Artificial (Other)
	    'arw' => 28,	# Arawak
	    'asm' => 29,	# Assamese
	    'ast' => 30,	# Asturian; Bable; Leonese; Asturleonese
	    'ath' => 31,	# Athapascan languages
	    'aus' => 32,	# Australian languages
	    'ava' => 33,	# Avaric
	    'ave' => 34,	# Avestan
	    'awa' => 35,	# Awadhi
	    'aym' => 36,	# Aymara
	    'aze' => 37,	# Azerbaijani
	    'bad' => 38,	# Banda languages
	    'bai' => 39,	# Bamileke languages
	    'bak' => 40,	# Bashkir
	    'bal' => 41,	# Baluchi
	    'bam' => 42,	# Bambara
	    'ban' => 43,	# Balinese
	    'baq' => 44,	# Basque
	    'bas' => 45,	# Basa
	    'bat' => 46,	# Baltic (Other)
	    'bej' => 47,	# Beja; Bedawiyet
	    'bel' => 48,	# Belarusian
	    'bem' => 49,	# Bemba
	    'ben' => 50,	# Bengali
	    'ber' => 51,	# Berber (Other)
	    'bho' => 52,	# Bhojpuri
	    'bih' => 53,	# Bihari
	    'bik' => 54,	# Bikol
	    'bin' => 55,	# Bini; Edo
	    'bis' => 56,	# Bislama
	    'bla' => 57,	# Siksika
	    'bnt' => 58,	# Bantu (Other)
	    'bos' => 59,	# Bosnian
	    'bra' => 60,	# Braj
	    'bre' => 61,	# Breton
	    'btk' => 62,	# Batak languages
	    'bua' => 63,	# Buriat
	    'bug' => 64,	# Buginese
	    'bul' => 65,	# Bulgarian
	    'bur' => 66,	# Burmese
	    'byn' => 67,	# Blin; Bilin
	    'cad' => 68,	# Caddo
	    'cai' => 69,	# Central American Indian (Other)
	    'car' => 70,	# Galibi Carib
	    'cat' => 71,	# Catalan; Valencian
	    'cau' => 72,	# Caucasian (Other)
	    'ceb' => 73,	# Cebuano
	    'cel' => 74,	# Celtic (Other)
	    'cha' => 75,	# Chamorro
	    'chb' => 76,	# Chibcha
	    'che' => 77,	# Chechen
	    'chg' => 78,	# Chagatai
	    'chi' => 79,	# Chinese
	    'chk' => 80,	# Chuukese
	    'chm' => 81,	# Mari
	    'chn' => 82,	# Chinook jargon
	    'cho' => 83,	# Choctaw
	    'chp' => 84,	# Chipewyan; Dene Suline
	    'chr' => 85,	# Cherokee
	    'chu' => 86,	# Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic
	    'chv' => 87,	# Chuvash
	    'chy' => 88,	# Cheyenne
	    'cmc' => 89,	# Chamic languages
	    'cop' => 90,	# Coptic
	    'cor' => 91,	# Cornish
	    'cos' => 92,	# Corsican
	    'cpe' => 93,	# Creoles and pidgins, English based (Other)
	    'cpf' => 94,	# Creoles and pidgins, French-based (Other)
	    'cpp' => 95,	# Creoles and pidgins, Portuguese-based (Other)
	    'cre' => 96,	# Cree
	    'crh' => 97,	# Crimean Tatar; Crimean Turkish
	    'crp' => 98,	# Creoles and pidgins (Other)
	    'csb' => 99,	# Kashubian
	    'cus' => 100,	# Cushitic (Other)
	    'cze' => 101,	# Czech
	    'dak' => 102,	# Dakota
	    'dan' => 103,	# Danish
	    'dar' => 104,	# Dargwa
	    'day' => 105,	# Land Dayak languages
	    'del' => 106,	# Delaware
	    'den' => 107,	# Slave (Athapascan)
	    'dgr' => 108,	# Dogrib
	    'din' => 109,	# Dinka
	    'div' => 110,	# Divehi; Dhivehi; Maldivian
	    'doi' => 111,	# Dogri
	    'dra' => 112,	# Dravidian (Other)
	    'dsb' => 113,	# Lower Sorbian
	    'dua' => 114,	# Duala
	    'dum' => 115,	# Dutch, Middle (ca.1050-1350)
	    'dut' => 116,	# Dutch; Flemish
	    'dyu' => 117,	# Dyula
	    'dzo' => 118,	# Dzongkha
	    'efi' => 119,	# Efik
	    'egy' => 120,	# Egyptian (Ancient)
	    'eka' => 121,	# Ekajuk
	    'elx' => 122,	# Elamite
	    'enm' => 124,	# English, Middle (1100-1500)
	    'epo' => 125,	# Esperanto
	    'est' => 126,	# Estonian
	    'ewe' => 127,	# Ewe
	    'ewo' => 128,	# Ewondo
	    'fan' => 129,	# Fang
	    'fao' => 130,	# Faroese
	    'fat' => 131,	# Fanti
	    'fij' => 132,	# Fijian
	    'fil' => 133,	# Filipino; Pilipino
	    'fin' => 134,	# Finnish
	    'fiu' => 135,	# Finno-Ugrian (Other)
	    'fon' => 136,	# Fon
	    'fre' => 137,	# French
	    'frm' => 138,	# French, Middle (ca.1400-1600)
	    'fro' => 139,	# French, Old (842-ca.1400)
	    'frr' => 140,	# Northern Frisian
	    'frs' => 141,	# Eastern Frisian
	    'fry' => 142,	# Western Frisian
	    'ful' => 143,	# Fulah
	    'fur' => 144,	# Friulian
	    'gaa' => 145,	# Ga
	    'gay' => 146,	# Gayo
	    'gba' => 147,	# Gbaya
	    'gem' => 148,	# Germanic (Other)
	    'geo' => 149,	# Georgian
	    'ger' => 150,	# German
	    'gez' => 151,	# Geez
	    'gil' => 152,	# Gilbertese
	    'gla' => 153,	# Gaelic; Scottish Gaelic
	    'gle' => 154,	# Irish
	    'glg' => 155,	# Galician
	    'glv' => 156,	# Manx
	    'gmh' => 157,	# German, Middle High (ca.1050-1500)
	    'goh' => 158,	# German, Old High (ca.750-1050)
	    'gon' => 159,	# Gondi
	    'gor' => 160,	# Gorontalo
	    'got' => 161,	# Gothic
	    'grb' => 162,	# Grebo
	    'grc' => 163,	# Greek, Ancient (to 1453)
	    'gre' => 164,	# Greek, Modern (1453-)
	    'grn' => 165,	# Guarani
	    'gsw' => 166,	# Swiss German; Alemannic; Alsatian
	    'guj' => 167,	# Gujarati
	    'gwi' => 168,	# Gwich'in
	    'hai' => 169,	# Haida
	    'hat' => 170,	# Haitian; Haitian Creole
	    'hau' => 171,	# Hausa
	    'haw' => 172,	# Hawaiian
	    'heb' => 173,	# Hebrew
	    'her' => 174,	# Herero
	    'hil' => 175,	# Hiligaynon
	    'him' => 176,	# Himachali
	    'hin' => 177,	# Hindi
	    'hit' => 178,	# Hittite
	    'hmn' => 179,	# Hmong
	    'hmo' => 180,	# Hiri Motu
	    'hsb' => 181,	# Upper Sorbian
	    'hun' => 182,	# Hungarian
	    'hup' => 183,	# Hupa
	    'iba' => 184,	# Iban
	    'ibo' => 185,	# Igbo
	    'ice' => 186,	# Icelandic
	    'ido' => 187,	# Ido
	    'iii' => 188,	# Sichuan Yi; Nuosu
	    'ijo' => 189,	# Ijo languages
	    'iku' => 190,	# Inuktitut
	    'ile' => 191,	# Interlingue; Occidental
	    'ilo' => 192,	# Iloko
	    'ina' => 193,	# Interlingua (International Auxiliary Language Association)
	    'inc' => 194,	# Indic (Other)
	    'ind' => 195,	# Indonesian
	    'ine' => 196,	# Indo-European (Other)
	    'inh' => 197,	# Ingush
	    'ipk' => 198,	# Inupiaq
	    'ira' => 199,	# Iranian (Other)
	    'iro' => 200,	# Iroquoian languages
	    'ita' => 201,	# Italian
	    'jav' => 202,	# Javanese
	    'jbo' => 203,	# Lojban
	    'jpn' => 204,	# Japanese
	    'jpr' => 205,	# Judeo-Persian
	    'jrb' => 206,	# Judeo-Arabic
	    'kaa' => 207,	# Kara-Kalpak
	    'kab' => 208,	# Kabyle
	    'kac' => 209,	# Kachin; Jingpho
	    'kal' => 210,	# Kalaallisut; Greenlandic
	    'kam' => 211,	# Kamba
	    'kan' => 212,	# Kannada
	    'kar' => 213,	# Karen languages
	    'kas' => 214,	# Kashmiri
	    'kau' => 215,	# Kanuri
	    'kaw' => 216,	# Kawi
	    'kaz' => 217,	# Kazakh
	    'kbd' => 218,	# Kabardian
	    'kha' => 219,	# Khasi
	    'khi' => 220,	# Khoisan (Other)
	    'khm' => 221,	# Central Khmer
	    'kho' => 222,	# Khotanese
	    'kik' => 223,	# Kikuyu; Gikuyu
	    'kin' => 224,	# Kinyarwanda
	    'kir' => 225,	# Kirghiz; Kyrgyz
	    'kmb' => 226,	# Kimbundu
	    'kok' => 227,	# Konkani
	    'kom' => 228,	# Komi
	    'kon' => 229,	# Kongo
	    'kor' => 230,	# Korean
	    'kos' => 231,	# Kosraean
	    'kpe' => 232,	# Kpelle
	    'krc' => 233,	# Karachay-Balkar
	    'krl' => 234,	# Karelian
	    'kro' => 235,	# Kru languages
	    'kru' => 236,	# Kurukh
	    'kua' => 237,	# Kuanyama; Kwanyama
	    'kum' => 238,	# Kumyk
	    'kur' => 239,	# Kurdish
	    'kut' => 240,	# Kutenai
	    'lad' => 241,	# Ladino
	    'lah' => 242,	# Lahnda
	    'lam' => 243,	# Lamba
	    'lao' => 244,	# Lao
	    'lat' => 245,	# Latin
	    'lav' => 246,	# Latvian
	    'lez' => 247,	# Lezghian
	    'lim' => 248,	# Limburgan; Limburger; Limburgish
	    'lin' => 249,	# Lingala
	    'lit' => 250,	# Lithuanian
	    'lol' => 251,	# Mongo
	    'loz' => 252,	# Lozi
	    'ltz' => 253,	# Luxembourgish; Letzeburgesch
	    'lua' => 254,	# Luba-Lulua
	    'lub' => 255,	# Luba-Katanga
	    'lug' => 256,	# Ganda
	    'lui' => 257,	# Luiseno
	    'lun' => 258,	# Lunda
	    'luo' => 259,	# Luo (Kenya and Tanzania)
	    'lus' => 260,	# Lushai
	    'mac' => 261,	# Macedonian
	    'mad' => 262,	# Madurese
	    'mag' => 263,	# Magahi
	    'mah' => 264,	# Marshallese
	    'mai' => 265,	# Maithili
	    'mak' => 266,	# Makasar
	    'mal' => 267,	# Malayalam
	    'man' => 268,	# Mandingo
	    'mao' => 269,	# Maori
	    'map' => 270,	# Austronesian (Other)
	    'mar' => 271,	# Marathi
	    'mas' => 272,	# Masai
	    'may' => 273,	# Malay
	    'mdf' => 274,	# Moksha
	    'mdr' => 275,	# Mandar
	    'men' => 276,	# Mende
	    'mga' => 277,	# Irish, Middle (900-1200)
	    'mic' => 278,	# Mi'kmaq; Micmac
	    'min' => 279,	# Minangkabau
	    'mis' => 280,	# Uncoded languages
	    'mkh' => 281,	# Mon-Khmer (Other)
	    'mlg' => 282,	# Malagasy
	    'mlt' => 283,	# Maltese
	    'mnc' => 284,	# Manchu
	    'mni' => 285,	# Manipuri
	    'mno' => 286,	# Manobo languages
	    'moh' => 287,	# Mohawk
	    'mol' => 288,	# Moldavian
	    'mon' => 289,	# Mongolian
	    'mos' => 290,	# Mossi
	    'mul' => 291,	# Multiple languages
	    'mun' => 292,	# Munda languages
	    'mus' => 293,	# Creek
	    'mwl' => 294,	# Mirandese
	    'mwr' => 295,	# Marwari
	    'myn' => 296,	# Mayan languages
	    'myv' => 297,	# Erzya
	    'nah' => 298,	# Nahuatl languages
	    'nai' => 299,	# North American Indian
	    'nap' => 300,	# Neapolitan
	    'nau' => 301,	# Nauru
	    'nav' => 302,	# Navajo; Navaho
	    'nbl' => 303,	# Ndebele, South; South Ndebele
	    'nde' => 304,	# Ndebele, North; North Ndebele
	    'ndo' => 305,	# Ndonga
	    'nds' => 306,	# Low German; Low Saxon; German, Low; Saxon, Low
	    'nep' => 307,	# Nepali
	    'new' => 308,	# Nepal Bhasa; Newari
	    'nia' => 309,	# Nias
	    'nic' => 310,	# Niger-Kordofanian (Other)
	    'niu' => 311,	# Niuean
	    'nno' => 312,	# Norwegian Nynorsk; Nynorsk, Norwegian
	    'nob' => 313,	# Bokmål, Norwegian; Norwegian Bokmål
	    'nog' => 314,	# Nogai
	    'non' => 315,	# Norse, Old
	    'nor' => 316,	# Norwegian
	    'nqo' => 317,	# N'Ko
	    'nso' => 318,	# Pedi; Sepedi; Northern Sotho
	    'nub' => 319,	# Nubian languages
	    'nwc' => 320,	# Classical Newari; Old Newari; Classical Nepal Bhasa
	    'nya' => 321,	# Chichewa; Chewa; Nyanja
	    'nym' => 322,	# Nyamwezi
	    'nyn' => 323,	# Nyankole
	    'nyo' => 324,	# Nyoro
	    'nzi' => 325,	# Nzima
	    'oci' => 326,	# Occitan (post 1500); Provençal
	    'oji' => 327,	# Ojibwa
	    'ori' => 328,	# Oriya
	    'orm' => 329,	# Oromo
	    'osa' => 330,	# Osage
	    'oss' => 331,	# Ossetian; Ossetic
	    'ota' => 332,	# Turkish, Ottoman (1500-1928)
	    'oto' => 333,	# Otomian languages
	    'paa' => 334,	# Papuan (Other)
	    'pag' => 335,	# Pangasinan
	    'pal' => 336,	# Pahlavi
	    'pam' => 337,	# Pampanga; Kapampangan
	    'pan' => 338,	# Panjabi; Punjabi
	    'pap' => 339,	# Papiamento
	    'pau' => 340,	# Palauan
	    'peo' => 341,	# Persian, Old (ca.600-400 B.C.)
	    'per' => 342,	# Persian
	    'phi' => 343,	# Philippine (Other)
	    'phn' => 344,	# Phoenician
	    'pli' => 345,	# Pali
	    'pol' => 346,	# Polish
	    'pon' => 347,	# Pohnpeian
	    'por' => 348,	# Portuguese
	    'pra' => 349,	# Prakrit languages
	    'pro' => 350,	# Provençal, Old (to 1500)
	    'pus' => 351,	# Pushto; Pashto
	    'que' => 353,	# Quechua
	    'raj' => 354,	# Rajasthani
	    'rap' => 355,	# Rapanui
	    'rar' => 356,	# Rarotongan; Cook Islands Maori
	    'roa' => 357,	# Romance (Other)
	    'roh' => 358,	# Romansh
	    'rom' => 359,	# Romany
	    'rum' => 360,	# Romanian
	    'run' => 361,	# Rundi
	    'rup' => 362,	# Aromanian; Arumanian; Macedo-Romanian
	    'rus' => 363,	# Russian
	    'sad' => 364,	# Sandawe
	    'sag' => 365,	# Sango
	    'sah' => 366,	# Yakut
	    'sai' => 367,	# South American Indian (Other)
	    'sal' => 368,	# Salishan languages
	    'sam' => 369,	# Samaritan Aramaic
	    'san' => 370,	# Sanskrit
	    'sas' => 371,	# Sasak
	    'sat' => 372,	# Santali
	    'scc' => 373,	# Serbian
	    'scn' => 374,	# Sicilian
	    'sco' => 375,	# Scots
	    'scr' => 376,	# Croatian
	    'sel' => 377,	# Selkup
	    'sem' => 378,	# Semitic (Other)
	    'sga' => 379,	# Irish, Old (to 900)
	    'sgn' => 380,	# Sign Languages
	    'shn' => 381,	# Shan
	    'sid' => 382,	# Sidamo
	    'sin' => 383,	# Sinhala; Sinhalese
	    'sio' => 384,	# Siouan languages
	    'sit' => 385,	# Sino-Tibetan (Other)
	    'sla' => 386,	# Slavic (Other)
	    'slo' => 387,	# Slovak
	    'slv' => 388,	# Slovenian
	    'sma' => 389,	# Southern Sami
	    'sme' => 390,	# Northern Sami
	    'smi' => 391,	# Sami languages (Other)
	    'smj' => 392,	# Lule Sami
	    'smn' => 393,	# Inari Sami
	    'smo' => 394,	# Samoan
	    'sms' => 395,	# Skolt Sami
	    'sna' => 396,	# Shona
	    'snd' => 397,	# Sindhi
	    'snk' => 398,	# Soninke
	    'sog' => 399,	# Sogdian
	    'som' => 400,	# Somali
	    'son' => 401,	# Songhai languages
	    'sot' => 402,	# Sotho, Southern
	    'spa' => 403,	# Spanish; Castilian
	    'srd' => 404,	# Sardinian
	    'srn' => 405,	# Sranan Tongo
	    'srr' => 406,	# Serer
	    'ssa' => 407,	# Nilo-Saharan (Other)
	    'ssw' => 408,	# Swati
	    'suk' => 409,	# Sukuma
	    'sun' => 410,	# Sundanese
	    'sus' => 411,	# Susu
	    'sux' => 412,	# Sumerian
	    'swa' => 413,	# Swahili
	    'swe' => 414,	# Swedish
	    'syc' => 415,	# Classical Syriac
	    'syr' => 416,	# Syriac
	    'tah' => 417,	# Tahitian
	    'tai' => 418,	# Tai (Other)
	    'tam' => 419,	# Tamil
	    'tat' => 420,	# Tatar
	    'tel' => 421,	# Telugu
	    'tem' => 422,	# Timne
	    'ter' => 423,	# Tereno
	    'tet' => 424,	# Tetum
	    'tgk' => 425,	# Tajik
	    'tgl' => 426,	# Tagalog
	    'tha' => 427,	# Thai
	    'tib' => 428,	# Tibetan
	    'tig' => 429,	# Tigre
	    'tir' => 430,	# Tigrinya
	    'tiv' => 431,	# Tiv
	    'tkl' => 432,	# Tokelau
	    'tlh' => 433,	# Klingon; tlhIngan-Hol
	    'tli' => 434,	# Tlingit
	    'tmh' => 435,	# Tamashek
	    'tog' => 436,	# Tonga (Nyasa)
	    'ton' => 437,	# Tonga (Tonga Islands)
	    'tpi' => 438,	# Tok Pisin
	    'tsi' => 439,	# Tsimshian
	    'tsn' => 440,	# Tswana
	    'tso' => 441,	# Tsonga
	    'tuk' => 442,	# Turkmen
	    'tum' => 443,	# Tumbuka
	    'tup' => 444,	# Tupi languages
	    'tur' => 445,	# Turkish
	    'tut' => 446,	# Altaic (Other)
	    'tvl' => 447,	# Tuvalu
	    'twi' => 448,	# Twi
	    'tyv' => 449,	# Tuvinian
	    'udm' => 450,	# Udmurt
	    'uga' => 451,	# Ugaritic
	    'uig' => 452,	# Uighur; Uyghur
	    'ukr' => 453,	# Ukrainian
	    'umb' => 454,	# Umbundu
	    'und' => 455,	# Undetermined
	    'urd' => 456,	# Urdu
	    'uzb' => 457,	# Uzbek
	    'vai' => 458,	# Vai
	    'ven' => 459,	# Venda
	    'vie' => 460,	# Vietnamese
	    'vol' => 461,	# Volapük
	    'vot' => 462,	# Votic
	    'wak' => 463,	# Wakashan languages
	    'wal' => 464,	# Walamo
	    'war' => 465,	# Waray
	    'was' => 466,	# Washo
	    'wel' => 467,	# Welsh
	    'wen' => 468,	# Sorbian languages
	    'wln' => 469,	# Walloon
	    'wol' => 470,	# Wolof
	    'xal' => 471,	# Kalmyk; Oirat
	    'xho' => 472,	# Xhosa
	    'yao' => 473,	# Yao
	    'yap' => 474,	# Yapese
	    'yid' => 475,	# Yiddish
	    'yor' => 476,	# Yoruba
	    'ypk' => 477,	# Yupik languages
	    'zap' => 478,	# Zapotec
	    'zbl' => 479,	# Blissymbols; Blissymbolics; Bliss
	    'zen' => 480,	# Zenaga
	    'zha' => 481,	# Zhuang; Chuang
	    'znd' => 482,	# Zande languages
	    'zul' => 483,	# Zulu
	    'zun' => 484,	# Zuni
	    'zxx' => 485,	# No linguistic content
	    'zza' => 486,	# Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki
	    );